### ISSUE TITLE
No copy buttons in Cura RC3

### ISSUE THREAD

**Issue by Karijn** [daid/LegacyCura#104]
The copy buttons are gone in RC 3, I know that there is a project now, but that option requires more space for the printhead and the fan.

**Comment by daid** [comment]
The multiply option is removed because it did not work at all with dual extruder support. It also solved an layout issue on MacOS.

I know the project planner isn't a perfect replacement for it, but I had to choose between doing a lot of work to get multiply to work in dual extrusion, or remove it. So I opt to remove it for RC3.

**Comment by daid** [comment]
The project planner in 12.08 also allows printing all the object at the same time, same as with the old copy buttons. So the copy buttons no longer have a reason to return.
