### ISSUE TITLE
cura utilization

### ISSUE THREAD

**Issue by richard10077** [daid/LegacyCura#1049]
I am going to use Cura for my home made 3d printer .however, I couldn't connect my device to this software.When I try to print or run bed leveling wizard ,it starts to read and open the port but it shows " closed" without any act . I would like to know if there are materials to study related to how to set and start the software.

**Comment by a4jp-com** [comment]
Another problem is this program does a 3 point calibration for people with heatbeds but homemade printers usually need 4 point calibration. I hope they add an option for 4 point calibration for people with heat beds soon.

**Comment by daid** [comment]
@a4jp-com I would like you to keep your issue separate instead of littering other issues with it.

@richard10077 Did you install firmware and which firmware? Also I recommend http://www.pronterface.com/ for initial testing of a home build printer, as it has a lot more bells and whistles to low level see what is happening.
