### ISSUE TITLE
Cura stop printing when printing a large object after 10 mins

### ISSUE THREAD

**Issue by rokaku** [daid/LegacyCura#1052]
I'm using 14.09 and 14.21 on Mac with prusa i3 compatible 3DP, when I print a small object it works good without any problem. But when I try to print dust and Cura stop printing around 10 minutes later, I had tried it several times, and it stops working almost at the same place.

I also try to do the same steps in Windows but I found the print button is greyed out so that I can't print anything. Please let me know if any logs is needed (and how/where to generate it).
Thanks in advance.

**Comment by a4jp-com** [comment]
If you have a large file I can try loading it.

**Comment by daid** [comment]
USB printing? Could be the general USB stability problem (pretty much effects people at random)

Easiest way to check is to save the GCode file and try to print it with:
http://www.pronterface.com/
Instead of Cura.

(Grayed out print button in windows is usually a problematic firewall that blocks local sockets)

**Comment by rokaku** [comment]
Hi All,

I'm using this one to test. It would be nice if anyone can help to test it on the Mac.
http://www.thingiverse.com/thing:540716

Yes, I'm using USB printing, not sure what is general USB stability problem? If so is there any workaround? I would like to have my Mac to work with my 3DP... 
Thanks again.

**Comment by daid** [comment]
The stability problem is that the USB drivers just stop working, at random, without a clear cause.

It has been happening on just about any printer. Which is why Ultimaker decided to make the Ultimaker2 SD printing only.

There are various "work-arounds" that work for some people, but not for everyone. For example, some people report that their problems are gone when they use a powered USB hub. Other people report that they had to remove the powered USB hub they where using.
Other workarounds are solutions like Octoprint, to enable web-based printing.

Note that this problem lays beyond the control of Cura. Cura simply sees no more data, nothing else. It's just as if the printer stopped doing anything.

**Comment by rokaku** [comment]
Okay, I got it. BTW, today I tried to print it using SD card successfully without any problem. The .gcode file was generated by Cura 14.12 build and it shows only 1 hour to print it (In 14.09 build it takes 1.5 hours). Originally I think something was optimized so the time was reduced to 1 hour only. But after printing I found the header was getting cut off. 

My printing object is from http://www.thingiverse.com/thing:540716 . There tested file name is fan_duct_V1. You can preview it in Cura, but here is my printed results. 
![20141224_124818](https://cloud.githubusercontent.com/assets/4890074/5547487/58aa9524-8b95-11e4-8d21-f65cae91f6d3.jpg) 

Then I tried to verify the generated .gcode file between R14.09 and R14.12 by printrun app, and it's indeed different for the geode, I think it's a bug for 14.12, please let me know if I have to open a new defect for it.

 Thanks again and Merry Xmas!!

**Comment by hg42** [comment]
daid:
"Note that this problem lays beyond the control of Cura. Cura simply sees no more data, nothing else. It's just as if the printer stopped doing anything."

I'm sorry, I have to disagree.
I never had USB printing issues with other software (pronterface, RepetierHost).
And I always got at least a few warnings while USB printing with Cura (retries) and some of those failed after a bunch of layers.
Any Cura generated gcode file having issues always printed without any warnings on those other software.
I also checked with a serial monitor if those other software do retries (eventually not telling the user), but they don't.
So I have to conclude there probably is a problem in Cura.

After a lot of failed parts, I now use Cura only as viewer and CuraEngine as slicer for pronterface while still USB printing.
Since then I had not a single issue with USB printing.

Currently I am using a Smoothieboard as controller for several months now.
I think I had USB printing issues with this and Cura, too, but I'm not totally sure if I remember this correctly. Perhaps I should try again.

But printing control with pronterface is currently much better than with Cura, e.g. I have programmable function buttons, I can send commands while printing and I can directly tweak printing speed (while still missing flow control like in RepetierHost).
So I would not print with Cura anyway.

**Comment by hg42** [comment]
note that pronterface is written in python, too. So it seems to be possible to communicate reliably with python. Perhaps you can take a look how pronterface does it's communication and in which areas you find differences?
