### ISSUE TITLE
error when loading model for first time in rc3

### ISSUE THREAD

**Issue by kymwatts** [daid/LegacyCura#106]
Hey Daid,

I tried out rc3 for the first time tonight.
I have loaded the stl, in basic mode cura and when i try to slice to gcode i get this error:

C:\Documents and Settings\kwatts\My Documents\stls\TESTBLOKJE.STL 0
Traceback (most recent call last):
  File "C:\Program Files\Cura_RC3\Cura\gui\simpleMode.py", line 273, in OnSlice
    profile.loadGlobalProfileFromString(oldProfile)
  File "C:\Program Files\Cura_RC3\Cura\util\profile.py", line 192, in loadGlobal
ProfileFromString
    (key, value) = option.split('=', 1)
ValueError: need more than 1 value to unpack

I am running windows xp 32bit.

let me know what i need to update to get this to work.

Thanks
Kym

**Comment by daid** [comment]
Yes, this bug slipped into RC3. I've fixed it already, and will release RC4 this weekend.

A quick workaround is:
-Use the menu "expert->normal mode"
-Goto the "start/end gcode" tab
-Click the "end.gcode" on the left
That's all, then it suddenly works. (the problem happens when you never touched the start/end code before)

For more info: http://forum.ultimaker.com/viewtopic.php?f=8&t=855

**Comment by daid** [comment]
This should be solved now in RC4.
