### ISSUE TITLE
Print every half layer like Netfabb

### ISSUE THREAD

**Issue by Bito** [daid/LegacyCura#11]
Maybe the skin function could be enabled to get the possiblity of printing perimeters every half layer height and infill every layer for smooth surface and fast infill.

Kind regards
Bito

**Comment by jgeerds-zz** [comment]
Please include a checkbox to enable skin (which is the equivalent to half-layeres in netfabb). the logical place would be next or under the layer height setting.
skin helps printing larger objects faster, since not so many layers are used for internal structures, yet the surface looks nice because it has a higher resolution. it also helps with overhangs.

**Comment by daid** [comment]
Actually, I don't trust the skin plugin at all. I copied it for the Joris plugin, and the Joris plugin had a few serious bugs because of it. (missing lines, lines going across the object for no reason)

I understand why people want skin, I understand what it improves. But I won't add it unless I find time to do enough tests with it. It might be fine and I could have made an error with the Joris plugin. But I do not want to take the risk.

**Comment by jgeerds-zz** [comment]
The skin plugin had performed quite nicely, I don't remember any issues... I've never used the Joris plugin (since my objects don't need it), but from the logic behind it, they are somehow exclusive, meaning you can have one or the other, not both at the same time. It would be great if you could give it a try to drop the skin plugin in, i'll test it

**Comment by daid** [comment]
Seems like I made a mistake when building the Joris plugin, and the skin plugin functions fine. So I've added a checkbox to enable 'skin'. It always does a "half layer" print, nothing configurable other then that.

**Comment by jgeerds-zz** [comment]
activating skin in 0626dae61c is producing all kinds of warnings and errors, including a divide by 0 (something went wrong)... I was probably wrong to assume the skin plugin would just work

**Comment by daid** [comment]
Oh, that's just the progress bar calculation that's going wrong, it didn't expect the skin plugin :P
