### ISSUE TITLE
Feature Request: Assign parts to specific extruder

### ISSUE THREAD

**Issue by camchaney** [daid/LegacyCura#1127]
I have just started to try out my dual extruder on my Lulzbot Taz. I uploaded the basic configuration file (http://devel.lulzbot.com/TAZ/accessories/dual_extruder/dual_extruder-1.0/Calibration/calibration_squares/Calibration_Squares.amf.xml) into Cura with no problems. The red and yellow colors (representing which extruder to use) of the model were in the right place and everything looked fine.

I started to think, though, how I would be able to re-assign the colors if I wanted to change the extruder that printed each part. I looked all around in Cura, but there was no way of assigning an extruder to a specific part of my model. Once you upload an amf file, or combine two parts with dual extrusion merge, there is no way of changing the extruder that they are assigned to.

This problem is really something that they should take care of in the next update. There should be some sort of option, when you click a part, to be able to change the extruder in which it is assigned.

**Comment by daid** [comment]
This will come in the GUI overhaul that we're working on.

**Comment by scknurr** [comment]
Bump!

**Comment by daid** [comment]
Counterbump!

**Comment by XiaoShiZi** [comment]
Playing pinball?
Op 3-mei-2015 10:38 schreef "daid" notifications@github.com:

**Comment by BagelOrb** [comment]
Pinball might be a feature of the new GUI as well, who knows?

**Comment by francoisba** [comment]
Hello, similar feature request here (https://github.com/daid/Cura/issues/675)
I add my vote ! ;)

Many thank to the developers

**Comment by turboderp** [comment]
So is this going to happen?

**Comment by nallath** [comment]
We don't have it yet, it is planned for a feature release.

**Comment by BagelOrb** [comment]
You can already assign an extruder to each object separately, but dual extrusion is not fully supported yet by the new Cura.

There are a lot of settings which you can change per object now! :D

**Comment by francoisba** [comment]
> You can already assign an extruder to each object separately

Hello everyone, thank you for your answers.
@BagelOrb, could you please tell us a bit more about that ?
Because I didn't find out how to do it. On which version of Cura is it possible ?

Thank you for your help

Edit -
Well, I found a plugin «Select Extruder», from Stefan Heule (Dim3nsioneer)
I will try using this later 😉
Thanks

Edit 2 -

So, actually, it works…
• Select which extruder use for one print (one or several parts): «Select Extruder» plugin, by Stefan Heule
• Assign extruder to specific part in dual extrusion : It depends on which part you selected first, before right click the second one and choose «dual extrusion assembly» (or something like that - I use the french version). So, the part right-clicked will be assigned to the second extruder : it's that easy !

**Comment by BagelOrb** [comment]
Thats actually on cura 2.0, which hasn't fully been released yet. You can
find a beta online which I think is called 15.10, but it is from a while
back and has quite some bugs in it.

Me saying that that was possible on an issue in this repository was kind of
misleading, since the repo for that cura is at Ultimaker.github.com/cura
Op 13 feb. 2016 19:05 schreef "francoisba" notifications@github.com:
