### ISSUE TITLE
suspected over-extrusion at corners - proposed algorithm to fix.

### ISSUE THREAD

**Issue by thethereza** [daid/LegacyCura#119]
I've been noticing that my right angle corners have a bit more material than it should making it bulge a bit.  I thought about this, and it seems to me that the approach of extruding a fixed amount for a length of travel, then changing angles and then extruding an amount proportional to the new length of travel will result in overextrusion at the corner by a factor of 2 over a small length.  

I've not gone through the code to see if this is what is being done, but that's what I suspect from what I see in the prints.

I can draw out the diagram showing the derivation - i started to but my drawing sucks - let me know if it's not obvious and i can try again.

The area of a corner for an for an arbitrary bend angle theta with extrusion width w is 

w^2*sin( (180-theta)/2)

if the corner was not there, then the area given the same length of travel would be

2_w^2_sin((180-theta)/2)

the solution is to break all lines that end in a corner into two lines.  The first line would extend up to  1/2_w_sin((180-theta)/2)  (which I will call x) before the corner.  The second small segment (x) would extrude only 1/2 as much.  Then after the corner, for a distance of x, you would also extrude 1/2 a much.  For the remaining length, you would extrude as normal.  

See this diagram for an illustration..

http://imgur.com/THY7A

**Comment by thethereza** [comment]
can you point me to where in the code something like this might live.  i tried to go through the code but there is a lot of it..

**Comment by daid** [comment]
First note, all this code for slicing is copied from Skeinforge. Which is a horrible mess really. I would not even know where to look for the exact details if you wanted to change this.

However, I do not think it's over-extruding at the corners. When it calculates the amount to extrude for a line it does this as a square box of material. So for the calculations, it actually deposits too much material at the inside corners, and too little material at the outside corners. This should balance out to about the right amount of material.

**Comment by thethereza** [comment]
I'm definitively getting bulging where there is 90 degree bend.  I would love to to figure out where this is computed in the source.

**Comment by daid** [comment]
Are you running Marlin firmware?

**Comment by thethereza** [comment]
Yes, is there a bug with it?

**Comment by daid** [comment]
No, not really. But older firmwars (pre-Marlin) could blob extra at corners.

**Comment by rewolff** [comment]
Guys. The effect is definitively real. 

What /I/ think is happening is the following:

The motors cannot start-stop at the high speeds the ultimaker runs at. On an "on grid" 90 degree corner, one motor needs to come to a stop, the other needs to accelerate to the printing speed. Before the corner, the firmware will slow down to be able to come to a stop for the first motor, then the second motor will accelerate to the printing speed. 

If all is good, also the "E" parameter will scale and slow down for the corner. However, there is a dynamic system in the extrusion: on first approximation, it is a first-order filter. The slowing and starting for such a corner is much faster than the time-constant of the filter, so extrusion continues more or less steady. So while the linear speed of the extrusion head is slowing down, E-speed is not, and too much is deposited. 

I have a bridge-and-overhang test-object. Ok... uploaded it: http://www.thingiverse.com/image:147312
Here I can clearly see the effect on the "lower levels". To my surprise a few moments ago, the effect was absent higher up in the model.... Until I realized that at those levels the printer was slowing down because of the "min layer time". So the stopping and starting takes much less traveled distance, and the over-extrusion of material is much less. 

So there I have confirmation of my hypothesis: it is related to the printing speed. (and not as originally supposed due to a math-error in the slicing code). 

P.S. I have "marlin". currently build-me-marlin with LCD support, previously stock ultimaker build.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
