### ISSUE TITLE
Build plate chessboard size 

### ISSUE THREAD

**Issue by dotBits** [daid/LegacyCura#1216]
As you can see on the right side of the screenshot, seems that the build plate chessboard is not wide enough.

![Image of Ultimaker2 buildplate checkboard](https://dl.dropboxusercontent.com/u/26565311/Ultimaker2_buildplate.jpg)

**Comment by mo22de** [comment]
I just wonder what happend to your settings menu, shouldn't be there more options?
Like printing Temperature
and Filament diameter an Flow?

At least thats what my Cura shows me. :-)

Cant imagine that the Ultimaker 2 Extended didn'T have the option to change that?

**Comment by dotBits** [comment]
this is a fresh install on Windows 7 and the configured machine is an Ultimaker2

**Comment by mo22de** [comment]
It's the same on Ubuntu with Ultimaker2 at my Computer and it seems like this is really out of usable space for printing too. So there might be a reason to that?

And my fault, it seems like Ultimaker has removed it since Ultimaker2 to the machines controller. :-/
So you have to click wheel those settings at the machine while switching filament.o_O

In my opinion a bad idea, but may you could setup a new machine in Cura with Ultimaker2 Settings as a custom machine.

Would be interesting what would happen. Also interesting would be why they do that, the only reason may would be variable temperatures and speeds during one print, but even that could be achieved using a setting that comes with the GCode.

I dont want to capture this issue-post, but anyone has the answer to that too.
The original qustion and/or Problem was the build plate chessboard size not matching the build plate.

**Comment by daid** [comment]
It matches the build volume just fine, the nozzle (which is on the left of the head) cannot reach the right area of the buildplate. (Just check it in your machine, you'll notice that there is still room on the buildplate when the head can no longer move to the right)

The older reprisentation of the build volume was actually wrong, it was the same size, but centered, meaning you lost a bit more volume on the virtual clips.

**Comment by dotBits** [comment]
@daid clear that it's just a visual issue for the chessboard and not for the build volume itself, what about to wrap the available printing area into a build plate container and draw the chessboard on its size?
