### ISSUE TITLE
Draw all perimeters one feature at a time.

### ISSUE THREAD

**Issue by nallenscott** [daid/LegacyCura#1319]
Cura is drawing one or two perimeters on a feature, then leaving to draw one or two on another feature and so on, until it eventually gets all the perimeters drawn for the entire layer. The resulting perimeters are pretty sloppy due to the starting / stopping (especially on smaller features). Is it possible to force Cura to draw all of the perimeters one feature at a time?

**Comment by Dim3nsioneer** [comment]
+1

**Comment by BagelOrb** [comment]
I don't understand your request.
I take it to mean that for each layer part the walls are printed first, then the rest and then on to the next layer part. But that has been the way Cura does it as long as I can remember.

If this really is the issue, please provide me with an STL on which the problem occurs.
Otherwise, what is the issue exactly?

Note: this is the repository of the old Cura front-end, while the issue is a back-end issue. See https://github.com/Ultimaker/CuraEngine for the back-end, and see https://github.com/Ultimaker/Cura for the new front-end.
