### ISSUE TITLE
The empty space is filled where no need for filling or support

### ISSUE THREAD

**Issue by ohhmm** [daid/LegacyCura#1422]
[The STL object](https://drive.google.com/file/d/0B7iRuJQSQAVWb25YQ0p2ZksydzA/view?usp=sharing) slice result gives no emptinnes in resulting gcode.
The Cura itself shows no the problem in UI. But [Gcode Simulator](https://play.google.com/store/apps/details?id=de.dietzm.gcodesimulator&hl=ru) and Pronterface shows it would be filled.
Another problem with the model and maybe the root problem is The Cura shows filled slice in couple of levels.

**Comment by daid** [comment]
Look in x-ray view, it will show that your model has a lot of holes. Cura will do it's best in this case, but can get confused.

**Comment by ohhmm** [comment]
Slic3r makes one hole without support. Cura fills the hole inside. Try 100%
Slic3r losts one gear though

**Comment by ohhmm** [comment]
Tried on latest stable version for windows

**Comment by daid** [comment]
Like I said, the model is broken, results will be unpredictable in any software.

**Comment by ohhmm** [comment]
What do you mean by broken? How you see it? OpenCascad shows good model.
Cura shows good model. But gcode it generates has problems.
1 марта 2016 г. 10:57 пользователь "daid" notifications@github.com
написал:

**Comment by BagelOrb** [comment]
Look at the x-ray view. If there are red parts your model is missing some
faces, or it has too many.

Try playing with the fix horrible settings in advanced. Maybe some
combination can fix your problem. Otherwise you have to fix the model
itself.

Openscad doesn't handle it very well when it performs a difference or a
union of two object which have a face in the same plane...
Op 1 mrt. 2016 10:18 schreef "Sergei Krivonos" notifications@github.com:

**Comment by ohhmm** [comment]
Maybe I missing something, but any problems of STL should be seen in Cura, but:
What I see in Cura is:
![cura](https://cloud.githubusercontent.com/assets/190779/13429130/5b80cd68-dfc7-11e5-8fda-1da0fb933789.png)
and what I see after printing is:
![imag1375](https://cloud.githubusercontent.com/assets/190779/13430098/4b967092-dfcc-11e5-96ba-4731aad5eb64.jpg)
again, Cura:
![2016-03-01 16 41 17](https://cloud.githubusercontent.com/assets/190779/13430153/86ece478-dfcc-11e5-812f-4aece7538763.png)
![2016-03-01 16 42 38](https://cloud.githubusercontent.com/assets/190779/13430179/a6752738-dfcc-11e5-8509-cdef1b26f7cb.png)
![2016-03-01 16 43 00](https://cloud.githubusercontent.com/assets/190779/13430190/b0dc7302-dfcc-11e5-8c75-22ef94214946.png)
![2016-03-01 16 43 26](https://cloud.githubusercontent.com/assets/190779/13430206/c019c70c-dfcc-11e5-881d-2e8815b45c04.png)
![2016-03-01 16 43 41](https://cloud.githubusercontent.com/assets/190779/13430215/c8a0eaf4-dfcc-11e5-9b9a-a2ba89922b66.png)
looks like it creates some solid part, but it is not. well, it should not:
![2016-03-01 16 45 20](https://cloud.githubusercontent.com/assets/190779/13430255/05d16bb0-dfcd-11e5-851d-cd4132e760a5.png)
![2016-03-01 16 45 49](https://cloud.githubusercontent.com/assets/190779/13430275/144c71ee-dfcd-11e5-962c-3d2914862c0f.png)
stlview.com shows good model too:
![2016-03-01 16 46 50](https://cloud.githubusercontent.com/assets/190779/13430346/4c8ae676-dfcd-11e5-92ec-205e40f3d928.png)
What is hex ray view? Of Cura. Everything well there too.
I would be gratefully thankful for any proposes.

**Comment by daid** [comment]
![image](https://cloud.githubusercontent.com/assets/964186/13432049/4c4f30be-dfcc-11e5-9734-1fb873c57333.png)

**Comment by nallath** [comment]
If there are red areas, your model is wrong, regardless of if your model is displayed correctly. There are red areas, so your model is non-manifold (http://blender.stackexchange.com/questions/7910/what-is-non-manifold-geometry)

**Comment by ohhmm** [comment]
You mean these intersection areas? Its not a problem to Cura. It was just bit esier to write drawing script. What problem is Where Cura those faces took from? There is no in STL. There should be a hole like Slic3r makes.

**Comment by nallath** [comment]
Cura took those faces from the model file. Those faces are there in the STL. There are a number of ways a bit of software can handle this, but not all of them work in every situation. Slic3r probably has different defaults from cura. Try messing with the fix horrible options in expert mode (or even better, fix the model)

**Comment by Ghostkeeper** [comment]
The problem essentially comes from that it can't determine what the inside of the model is, so it doesn't know what to fill. Like if you have a house without a roof on top, everything inside the house becomes "outside".

In iHateInventNames' case, it looks like there are extra surfaces inside the model. The program then doesn't know what faces to use. If it chooses the extra surfaces your base becomes round and the teeth would be assumed to be non-watertight or "outside". If it chooses the teeth then only the teeth would appear and the base would become non-watertight or "outside". So what happens varies from program to program. In Cura's case it was decided that there would be no programming to account for that case at all. Therefore the result is unpredictable.

The extra surfaces are, of course, only visible in Normal view if you move the camera inside your model. Since that is a hassle, there is also the X-Ray view where you can more easily detect such cases: It colours them red.

**Comment by ohhmm** [comment]
If I'd eliminate these issues would someone look onto the problem? If yes, I'll send updated model tomorrow.

**Comment by ohhmm** [comment]
Thank you, that helped. Sory for bothering you guys. I fixed model with 3d builder automaticaly. Can we hope Cura could do that in feature?

**Comment by BagelOrb** [comment]
Let's hope so.
