### ISSUE TITLE
1.faster slicing - 2.printer stops

### ISSUE THREAD

**Issue by elrico1** [daid/LegacyCura#146]
cura 4 is fantastic, I love it, thank you so much for your work!!

but
1. slicing is realy f.... slow, sometimes it needs few hours, for "easy" objects, would be nice if you could make it faster,... maybe by a 64bit version? at the moment I do have enough (to much) recources left to work in other programs
2. when i try to print big objects the printer stops to print by itself at a hight of +- 5mm, and the nozzle stays hot?-danger-!!

I use windows7 ultimate 64bit
i7 processor 3.3gh
12gb ram
ssd disk

**Comment by daid** [comment]
1. I've already improved slicing time over 400% compared to the software on which it is based. Slicing is a difficult process, and the software I used as base doesn't make it easy to optimize it any more. Making your model less complex helps. But I've never had a slice take more then 15 minutes on my Core2 2.4Ghz machine. So maybe your model is not as simple as you think. Note that slicing time increases a LOT as the model gets more complex and if the model is larger.
2. I've never had the printer suddenly stop. Does this happen all the time at the same point? And is anything shown at the console window? Also, try to see if there is a difference if you print with the supplied "PrintRun" instead of Cura's own printing interface.

**Comment by jgeerds-zz** [comment]
sudden printer stops are almost always due to ESD, or other spikes in the power supply. large machines (i.e. vaccum cleaners) can cause this, especially in countries with poor electrical systems (i.e. US). using a power strip with surge protection helps in those cases, or identify which machine is causing the spike, and don't use it while printing. on the other hand, yes there are occasionally random stops, and the randomness makes it hard to track the issue.

**Comment by daid** [comment]
Closing this, because the slicing speed cannot be solved. And the sudden printer stops are almost always related to MIN/MAX temp errors. (which is a mechanical problem)
