### ISSUE TITLE
cura is not recognizing my printer

### ISSUE THREAD

**Issue by johnjroe** [daid/LegacyCura#1484]
I've done everything I can to resolve this issue myself. My computer recognizes that I have it hooked up but Cura won't... is there some trick that I'm overlooking? Any hints? Ideas? I have a Prusa Mendel i3

**Comment by BagelOrb** [comment]
What type of printer do you have? How do you hook it up?
Op 29 mei 2016 04:11 schreef "johnjroe" notifications@github.com:

I've done everything I can to resolve this issue myself. My computer
recognizes that I have it hooked up but Cura won't... is there some trick
that I'm overlooking? Any hints? Ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/daid/Cura/issues/1484, or mute the thread
https://github.com/notifications/unsubscribe/AIe9EZGysqd57kZg6-oe95GHr1E4Yniiks5qGPW8gaJpZM4IpMi1
.

**Comment by johnjroe** [comment]
Order 002-6920844-5646614
Usb

**Comment by BagelOrb** [comment]
I don't know much about order numbers. What printer do you have? An
Ultimaker 2+?
Op 29 mei 2016 12:01 schreef "johnjroe" notifications@github.com:

> Order 002-6920844-5646614
> Usb

**Comment by johnjroe** [comment]
I'm sorry... I thought my email was from customer service. It's a Mendel Prusa i3

**Comment by johnjroe** [comment]
Figured it out

**Comment by Ghostkeeper** [comment]
Ah, good. For posterity, what was the problem?

**Comment by johnjroe** [comment]
The serial port needed to be on com 3, not Auto.
