### ISSUE TITLE
Time Estimate

### ISSUE THREAD

**Issue by fergussonb** [daid/LegacyCura#1495]
Can anyone point me to where they calculate the time and material estimates? Thanks in advance.

**Comment by BagelOrb** [comment]
Time: https://github.com/Ultimaker/CuraEngine/blob/master/src/timeEstimate.cpp
Material is not so much an estimate; it's more like converting the difference in E-values, so I think that won't be that interesting to you.

In order to get an accurate energy estimate, I think you should calculate the energy for every move, then add up the energy to keep the hotend and bed heated based on the time estimates.

**Comment by BagelOrb** [comment]
Note that TimeMaterialEstimates (https://github.com/Ultimaker/CuraEngine/blob/master/src/gcodePlanner.h#L56) are naive estimates, which are far from accurate.These are used in an earlier stage of processing where the eventual paths aren't fully known yet.

**Comment by fergussonb** [comment]
Thanks do you know which part of the Cura GUI code displays the time estimate?

**Comment by BagelOrb** [comment]
You should take a look at the material cost calculator plugin
https://ultimaker.com/en/community/16693-print-cost-calculator-plugin
Op 8 jun. 2016 17:07 schreef "fergussonb" notifications@github.com:
