### ISSUE TITLE
why it print the layer at the wrong place

### ISSUE THREAD

**Issue by snuchitp** [daid/LegacyCura#1514]
I need to use this version because of my 3D printer. New version not support DeltaBot.
Please do not close my issue. I need some help

I used cura v 15.04.6 to display my model.  From layer 1-9, it looked correct that built each layer up on top. But from layer 10- the end  started to build from the bottom of the model. The detailed lines are different too.

layer 0-9
![screen shot 2016-07-01 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/12837769/16528681/57645856-3f8c-11e6-9dc0-2d558b7e7f1e.png)

layer 10 -14
![screen shot 2016-07-01 at 12 59 06 pm](https://cloud.githubusercontent.com/assets/12837769/16528683/5bf05032-3f8c-11e6-9692-c90ec3e63927.png)

Thanks

**Comment by BagelOrb** [comment]
It's not totally clear, but I think you are talking about the fact that the
lower layers are displayed as thin lines.

Note that this is only a display issue. Lower layers show thin lines so
that the rendering can go faster. This has nothing to do with the actual
gcode.

Only the top few layers show how the gcode actually is.
Op 1 jul. 2016 19:46 schreef "snuchitp" notifications@github.com:

I need to use this version because of my 3D printer. New version not
support DeltaBot.
Please do not close my issue. I need some help

I used cura v 15.04.6 to display my model. From layer 1-9, it looked
correct that built each layer up on top. But from layer 10- the end started
to build from the bottom of the model. The detailed lines are different too.

layer 0-9
[image: screen shot 2016-07-01 at 12 58 50 pm]
https://cloud.githubusercontent.com/assets/12837769/16528681/57645856-3f8c-11e6-9dc0-2d558b7e7f1e.png

layer 10 -14
[image: screen shot 2016-07-01 at 12 59 06 pm]
https://cloud.githubusercontent.com/assets/12837769/16528683/5bf05032-3f8c-11e6-9692-c90ec3e63927.png

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/daid/Cura/issues/1514, or mute the thread
https://github.com/notifications/unsubscribe/AIe9EbOpYL1k1mB0QCcrvvcNDSHdwYMvks5qRVJugaJpZM4JDWQK
.

**Comment by snuchitp** [comment]
layer 0-2 should be think lines
layer 3-21 should be thin lines
layer 22-24 should be thick lines 

The model should look like this

![screen shot 2016-07-01 at 3 07 04 pm](https://cloud.githubusercontent.com/assets/12837769/16532065/84f6e246-3f9d-11e6-8dc0-c6d2b1a942e0.png)

**Comment by snuchitp** [comment]
layer 0-2 should be thick lines

Top view

![screen shot 2016-07-01 at 3 09 56 pm](https://cloud.githubusercontent.com/assets/12837769/16532143/fc1ee3b4-3f9d-11e6-80d3-860908d1d0c0.png)

side view

![screen shot 2016-07-01 at 3 10 04 pm](https://cloud.githubusercontent.com/assets/12837769/16532149/0ae5bd32-3f9e-11e6-8048-914ab88c8ab8.png)

**Comment by snuchitp** [comment]
layer 3-21 should be thick lines

Top view

![screen shot 2016-07-01 at 3 12 53 pm](https://cloud.githubusercontent.com/assets/12837769/16532246/d0a500b4-3f9e-11e6-9490-2d5ff49bb308.png)

side view

![screen shot 2016-07-01 at 3 13 26 pm](https://cloud.githubusercontent.com/assets/12837769/16532249/d459cd16-3f9e-11e6-849b-98b01e8cd95a.png)

**Comment by BagelOrb** [comment]
I don't really understand. Could you attach your model in a zip file?
Op 1 jul. 2016 21:17 schreef "snuchitp" notifications@github.com:

**Comment by Ghostkeeper** [comment]
I suspect that what happens is that the new layers actually do get built on top of the old ones, but since the camera moves along with the highest layer, it looks like there are new layers on the bottom when you scroll up.

**Comment by daid** [comment]
This is a rendering optimalization. Lower layers then you are viewing are rendered quicker.
