### ISSUE TITLE
Can't move up and down in Cura

### ISSUE THREAD

**Issue by shingabiss** [daid/LegacyCura#1534]
You can zoom and rotate but sometimes one needs to go up and down in the space, can't seem to find a way to do that.

**Comment by nallath** [comment]
Shift click works for cura 2.x

**Comment by daid** [comment]
Legacy Cura has no way to move up/down the view location except for clicking on objects.

**Comment by BagelOrb** [comment]
In legacy cura you can go to the layer view, change the layer and go back
to normal view to change the height of the focus point of the camera.

Op 30 aug. 2016 09:52 schreef "daid" notifications@github.com:

Legacy Cura has no way to move up/down the view location except for
clicking on objects.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/daid/Cura/issues/1534#issuecomment-243361003, or mute
the thread
