### ISSUE TITLE
The Start/End-GCode text entry window does not scroll

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#16]
On my computer (OS X 10.7.3) I am not able to scroll the start/end GCode editing area down. It's as if the bottom of the editing area is being masked instead of resized when I resize the SkeinPyPy window such that the editing area can not display the entire text.

Here's an image showing the bottom end of the scroll bar being cut off by the bottom of the editing area: http://i1162.photobucket.com/albums/q531/lawrencejohnston/Github/SkeinPyPyNoScrolling.png

**Comment by daid** [comment]
This also happens in linux/windows, but in a slightly different way. It happens because you made the window so small the controls on the 2nd tab no longer fit. And thus the tab strip with contents doesn't get smaller then that. I should enforce some minimum size on the whole window, but with the growing window on slice that's not the simplest thing.

**Comment by RedwoodForest** [comment]
Thanks, that makes sense. I confirmed that if I make the window bigger the editing area does start scrolling correctly.

**Comment by RedwoodForest** [comment]
This is not completely fixed on my machine.

The editing area scrolls correctly when SkeinPyPy is first opened, but as soon as I enlarge the window it breaks again. Even if I enlarge it a couple of pixels the old behavior comes back.

The minimum size does seem to be enforced (I can't make the window any smaller than it is by default).
