### ISSUE TITLE
Project Planner does not warn you if one of your objects is too high

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#185]
The project planner does not warn you if one of the objects you're printing is tall enough that it will interfere with the axes holding the hot end during the printing of later object(s).

I almost had a major failure the other day when I printed a tall object (~95mm) followed by another object. Luckily I was watching the machine and caught it just before it crushed the first object.

I would expect the project planner to warn about this case the same way it does about printing objects too closely together.

Additionally in the case of only one tall object that would interfere with the axes, the auto place functionally could ensure that this object is printed last.

**Comment by daid** [comment]
I know. (I did kinda forget about it)

The problem is quite complex, as you have the X/Y gantry which have different heights and an offset from the printer head. There are multiple solutions, you could just add extra "collision" information about the gantry. But you can also print up to 80mm of each model, and then print the next 80mm.

A simple warning would also help, so I think I will add that first.

**Comment by RedwoodForest** [comment]
That makes sense.

A warning would indeed be a big help (even if it's conservative about what it warns about). The thought to check the height just didn't even cross my mind when I was laying out my objects.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
