### ISSUE TITLE
Cura makes extra retractions when "Retract on jumps only" is disabled.

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#186]
When "Retract on jumps only" is disabled Cura retracts even on moves shorter than the value set under "Minimum Travel".

I was printing what is essentially a thin-walled (walls 4 nozzle widths thick) box and Cura regularly retracts and then immediately extrudes while moving the head very little.

Here is an excerpt from the GCode. The retract occurs at the end of layer 94 and the extrude at the start of layer 95, even though there is very little x/y/z movement (less than 5mm, my configured value for "Minimum Travel"):

;TYPE:WALL-OUTER
G1 X64.8 Y67.3 F9000.0
G1 X64.8 Y132.7 F6000.0 E14.7788
G1 X135.2 Y132.7 E15.6617
G1 X135.2 Y67.3 E16.4818
G1 X64.8 Y67.3 E17.3646
G1 F3900.0
G1 E13.8646
G1 F6000.0
G92 E0
;LAYER:95
;TYPE:WALL-INNER
G1 X64.4 Y66.9 Z19.3 F9000.0
G1 F3900.0
G1 E3.5
G1 F9000.0
G1 X64.4 Y133.1 Z19.3 F6000.0 E4.3302
G1 X135.6 Y133.1 E5.223
G1 X135.6 Y66.9 E6.0532
G1 X64.4 Y66.9 E6.9461

Let me know if you need me to email you the STL or the entire GCode.

**Comment by daid** [comment]
I think this "extra" retraction only happens when there is a Z move. Can you confirm this?

**Comment by RedwoodForest** [comment]
Yes. They seem to happen every layer change.

**Comment by daid** [comment]
Interesting fact, I was reading the code to see if I could find this problem. And it seems that the Z distances is multiplied by a factor before it is used in the minimal distance calculation.

This factor depends on the Z speed and the travel speed. Because the Z speed is lower the amount of Z travel minimum distance is adjusted by this speed difference. For example, if you have 0.1mm layers, and a travel speed of 150mm/s and a Z speed of 3mm/s. Then it calculates: "0.1mm \* (150/3) = 5mm distance" for the Z.

I can see why it has been made like this, but I'm not sure if I agree with it.

**Comment by RedwoodForest** [comment]
That is interesting. Like you, I guess I see why, but I'm not sure I agree with it.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
