### ISSUE TITLE
FR: infill flow control

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#19]
By infill suffers from high speed and too low infill, it becomes crumbly and disjointed, and generally doesn't give enough support, and certainly doesn't take up 25% of the volume... (150mm/s 0.1mm 0.5mm nozzle)

have a look at this:
https://picasaweb.google.com/lh/photo/WsXT564o6kUJutUKjYvLXjIYJXjTqlQYmaNWFtjfw8o?feat=directlink

left is the (super slow) and controlled netfabb infill, on the right side the disjointed and insufficient spp infill (slic3r has the same issues).

adding a simple infill multiplier would help a great deal (as I had requested originally when I made the comments about the beta1  GUI))

**Comment by daid** [comment]
I don't think the best solution is to increase the flow rate for the infill. Because it will also affect the top/bottom infill. Also, you can see that there is enough material, it's just not attached at the right place. Lowering the print speed helps in this case, increasing the temperature might help.

Thicker top/bottom settings will ensure you don't have holes in the top/bottom. I had a print that looked the same, but with 6 top layers on that "bad" infill it was a solid part again.

Also, Skeinforge won't let me adjust just the infill speed/flowrate. Making this request pretty hard to implement.
(The advanced-realtime-tuning however, will solve this ;-) )

**Comment by jgeerds-zz** [comment]
I am live tuning/tweaking with M221 right now, but this affects the other extrusions also. printing slower is a solution, but not very satisfactory, since infill is the most boring part of printing, but it is necessary.

just to clarify the nomenclature: infill is the grid pattern that is used to fill in the "empty" inner space on an object.
top/bottom layers are not infill, they are a separate item, called solid layers (or similar)

I addition, it is absolutely not enough material to make a good and sound structure. I need good infill since I am printing real products, and not desktop objects.

One way around it could be utilizing the width/height setting for infill in SF, and this goes back to my initial FR for your gui:
------- snip --------
-- infill: same paradigm as above: give the user 2 choices to achieve the same: first 2 radio button options: infill rate (in percent) and infill spacing (in mm) combined with the extrusion width (in mm): this gives the user a wide range of design options that will suit them for many tasks: 10% infill with 0.8mm will create a relatively empty scaffolding like inside, which can be filled with epoxy, or other liquids, while 0.8mm spacing and 0.4mm extrusion will give a good&dense infill. again, the idea is to give parameters that can be understood by a human, while all the math can happen under the hood. the same warnings as above should apply. I would even maybe include a speed setting here, to enable printing infill as close to the max speed as possible, since this is the most boring part of my prints. maybe SF can make good estimates what the max extrusion rate is, based on nozzle, temp, mL/sec, filament diameter and user prefs/experience, and make a good suggestion, or even adjust the speed value when the user changes the extrusion width (i.e. at 0.5mm the suggested max is 150mm/s, while at 0.4mm the suggested max changes to 200mm/s (depending on layer height). with those 3 parameters, users should be able to adjust their infill to achieve what they need. an added bonus would be an adjustment factor, similar to the extrusion in the repG live tuning window: if the infill really gets discontinues (because bridging is too hard at that given moment), the user can re-slice, and only adjust the infill to i.e. 130% just to get the threads connected.
------- snip --------

I am fine with leaving the infill setting at xx% (setting it to 25% doesn't seem to generate 25% of PLA volume, it looks more like 15%), but some form of adjustment, either lowering the speed for infill, and/or increasing the flow (up to the extruder max we calculated before), is somehow mission critical for me.

in addition, and I filed the same FR with slic3r, the first solid layer above infill should be considered a bridge.

**Comment by daid** [comment]
The problem is, Skeinforge does not see the "infill" and the "solid layers" as different things. Internally they are both "infill".
The "fill" step from Skeinforge is one huge mystery to me. And it looks like Slic3r does it a lot smarter.

Commit 4c176dc72819180df9592cf3219e049d1f7de94a added a "Print speed validator", which works by using a "max volume per time" to guess if you can really print as fast as you are trying to print. However, this is more to protect against filament slipping.

I understand your problem, but there is really nothing I can do about it, except say, print slower. Increase the infill %, and hope that someday Slic3r has the features needed to make me switch.

**Comment by jgeerds-zz** [comment]
a good work around is using the grid or hex infill settings (20% is already pretty solid), instead of the flimsy/crumbly line infill

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
