### ISSUE TITLE
dll missing error message

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#2]
skeinpypy win32 B3: when I start the skeinpypy.bat, i get an error message: "python.exe - system error: the program can't start because MSVCR71.dll is missing from your computer. try reinstalling the program to fix this problem. OK" otherwise, it seems to run fine.

**Comment by daid** [comment]
This was noticed before. Not sure which part is causing this (MSVCR71 is part of visual studio, which I didn't use)
Installing the .NET runtime 1.1 gets rid of the message, because it includes the missing DLL file. I'll see if I can hunt down which file causes this, and why it still works without the DLL.

**Comment by daid** [comment]
The file that causes this issue is "gle32.dll", skeinpypy doesn't depend on it and it can be removed. It's in /python/Lib/OpenGL/DLLS/
I've updated the build script to remove this offending DLL for the next version.
