### ISSUE TITLE
FR: Different perimeter and infill speeds

### ISSUE THREAD

**Issue by Aggresive** [daid/LegacyCura#214]
Is this a planned feature? It makes a lot of difference in print time while maintaining quality.

**Comment by daid** [comment]
Depends on how you look at it.

Infill could mean different things. For some it's just the "internal" parts, which is the line grid. SF internally calls this "sparse infill", then you have bridges and top/bottom infill (also called up/down-skin sometimes).
All these things are called "infill" in skeinforge, and thus get the same speed and extrusion. (so far attempts to separate this have failed)

If you want different speed for the sparse infill, don't hope on it. If you want different speed for the infill + top/bottom, then you can do this already if you use Cura's printing interface (instead of Printrun), as Cura can adjust this speed at real time for different parts of the print. (useless if you use the UltiController)

For a configuration setting, the issue here is mainly the GUI. I don't want 10.000 options that confuse users even more. So far the single print speed setting has served it's goal pretty well.

**Comment by martinxyz** [comment]
Also, in my experience whenever the extruder speed changes, you get either too much or too little material for the moves that follow. The actual rate of what's coming out of the nozzle does not follow the extrusion rate immediately. As long as this is not accounted for, I'm sceptical about using different speeds.

**Comment by IdolCrasher** [comment]
I think he wants fast infill and slow outer perimeter a la Slic3r

**Comment by daid** [comment]
The extrusion "delay" problem might be countered by not changing the speed instantly but more gradually.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
