### ISSUE TITLE
PrintRun  Print command deosn't work

### ISSUE THREAD

**Issue by at101** [daid/LegacyCura#216]
The g-code file is generated from Cura 12.08 When the g-code file is loaded in PrintRun and the print button is clicked.
The print job never starts. The heater is turned off.
## When sending the g-code file to the Ultimaker, from PrintRun, the following error is seen in the console:

SENDING:M105
ok T:222.8 /230.0 B:0.0 /0.0 @:0
Print Started at: 15:38:47
T:229.5 E:0 W:?
T:230.4 E:0 W:?
T:230.9 E:0 W:?
T:231.2 E:0 W:?
T:231.4 E:0 W:?
T:231.9 E:0 W:?
T:231.9 E:0 W:?
T:231.9 E:0 W:?
T:231.9 E:0 W:?
T:231.9 E:0 W:?
T:231.9 E:0 W:?
-----------------------------------and it keeps on going.

Anybody have any clue how to fix this?

**Comment by daid** [comment]
That's no error, the T:231 reports are temperature reports, it's waiting for the temperature to settle at 230C. If it never settles then there might be something wrong with your PID settings.

**Comment by at101** [comment]
thanks for the response. The heater is set to preheat to 230 deg C. I press the Print button as soon as it gets close to the 230 mark. Should I wait until it reaches and stabilizes at that tmeperature before starting the Print job?
this report or unstable temperature doesn't happen all the time. What are the PID settings and how to correct them?

Also i ahve noticed, the heater gets turned off and temperature keeps dropping, is that also due to wrong PID settings?

**Comment by daid** [comment]
The T:xxx reports with E: and W: are a result of the M109 command. This command sets the target temperature and waits for the temperature to reach that point and settle. So there shouldn't be a reason to pre-heat yourself.

If the heater gets turned off and the temperature drops because of that then you might have a MINTEMP or MAXTEMP error in between? This error shuts off the heater because it doesn't trust the temperature sensor. (usually happens if your temperature sensor wires are a bit lose)

The PID should not need calibration for the Ultimaker. but how long did you wait for the temperature to settle when you saw the T:xxx reports?

**Comment by at101** [comment]
Thanks again. I did wait about 10-15 secs for the T:xxx reports to settle but most of the time they didn't. So I guess, when the g-code slicing is done in Cura, the temp. should be defined in one of the settings there? The M109 command would be taking care of the heating up through the g-code in Print Run? ok i'll try that and let you know the result.

**Comment by at101** [comment]
Yes finally it works, I was setting the temp twice In Cura = 210 deg C, and then printrun, preheat = 230 deg C. So i saw the temperature reports for the first tie and it confused me, maybe it will be helpful to display a GUI message fo r the user to say- "warming up" or  showing a bar going from blue to red etc. thanks
