### ISSUE TITLE
Feature Request: Multiple STLs

### ISSUE THREAD

**Issue by avalero** [daid/LegacyCura#228]
It would be great to be able to add several STL files and then organize them on the plate. Or make more than one copy of the same STL (like multiply)

**Comment by mfeherpataky** [comment]
It is already there. Called project planner located in the principal menu.

There is a bug however, which will send your hotend to Z0, back through
freshly printed object. Watch out and review the end of the gcode.
Otherwise it works great and as you describe it.

On 06 Oct 2012, at 21:16, "Alberto Valero-Gómez" notifications@github.com
wrote:

It would be great to be able to add several STL files and then organize
them on the plate. Or make more than one copy of the same STL (like
multiply)

—
Reply to this email directly or view it on
GitHubhttps://github.com/daid/Cura/issues/228.

**Comment by avalero** [comment]
Great. Thanks!!

**Comment by daid** [comment]
Indeed the project planner allows this, it also allows you to print multiple objects one after each-other (which is useful with a large printer bed)

See bug: https://github.com/daid/Cura/issues/220 for details about the "going to Z0 after printing" bug.

**Comment by daid** [comment]
Also, we are planning to merge the project planner into the main interface, but this will be a major interface overhaul. So don't expect it soon.

**Comment by avalero** [comment]
Looking forward to it... anyway. The program is great as it is... the rest
are aesthetic improvements.... which would make it awesome.
