### ISSUE TITLE
Connection problem (get "Machine state:closed" but pronterface prints well)

### ISSUE THREAD

**Issue by honnet** [daid/LegacyCura#240]
Hi,
Cura tells me  "Machine state:closed" when I try to print but pronterface can print well, at least the calibration cube (I didn't keep pronterface connected when using cura).
Do you know where I should start looking to try fixing that ?
Thanks !
Cedric.

Note: I use Marlin firmware @ 250000 baud in the portabee reprap, on the other side I have ubuntu 12.04 LTS with the cura repo cloned with git (the "stable" version doesn't connect better).

**Comment by daid** [comment]
the git-repo works better then the "stable" version (a new version will be released soon). So that's good.

Does it show the "error log" button after the machine state becomes closed? The newer version of Cura keeps quite a log about what it's been doing on the serial interface to diagnose these kinds of problems. However, you can only access this log in a case of an error, not in the closed state. You could hack line 345 of gui/printWindow.py:

  self.machineLogButton.Show(self.machineCom != None and self.machineCom.isError())

Just turn it into:

  self.machineLogButton.Show(True)

This will allow you to access the log. (I also pushed a patch which now shows the error log button if the state gets to closed)

**Comment by honnet** [comment]
Thanks to @MaurinElectroTextile I found that Cura doesn't support 250000 baud (with my machine).
The communication is now working perfectly @ 115200 ;)
Thanks again !
