### ISSUE TITLE
origin in bed center

### ISSUE THREAD

**Issue by doublemind** [daid/LegacyCura#266]
The current origin is fixed on the left front corner. the origin on a delta robot machine is in the center of the build area. Option for delta robot would be great. Now I have the model always an the left corner of the graphic area. (using 0,0 for machine center)

**Comment by daid** [comment]
I happily await patches for this from deltabot users. The visual part in the main window should be easy to fix, the project planner would require more work.

**Comment by AnthonyVH** [comment]
Could you give a hint as to where modifications to the code would be necessary?

**Comment by ghost** [comment]
Was the machine center option in version .10 a patch? If not, it would be real cool if it was just put back in...

**Comment by Intrinsically-Sublime** [comment]
You can just open your config ini file and set machine_center_x and machine_center_y manually. For the center at zero you could just set them to 0.01 and it will ignore the auto centering that was just added. (0, 0) will auto center at half of the machine width.

**Comment by ghost** [comment]
Thanks, Sublime. I tried your suggestion with 0.01 and 1.0 but got the same result; all g-code x/y values are positive and it sends my delta into the rails...

**Comment by Itchetiky** [comment]
Firstly, I really love how Cura slices. I enjoy how easy it is to configure the slicing, and it is so wonderful to see the printer take an intelligent path as it prints. The other slicer generates a much more randomly sliced 'thing' resulting in a chaotic path as the printer prints. I could go somewhere else for slicing, but Cura is just beautiful at it and I want to use it for my RepRap.

Please beat this down if its incorrect.

This pertains to the OS X version. It looks like Cura 12.12 is handling things differently for finding the center of the bed. In 12.11 and 12.10, machine_center_x and machine_center_y look to have been being auto-populated into the current_profile.ini file. This seems to have not been carried over to 12.12, where a different method is used.

To make things trickier, Cura 12.12 also changed the name of the centering variables it uses from machine_center_\* to object_center_*. This was found after examining the commit diff and Python code.

Manually entering the object_center_\* values in .cura/12.12/current_profile.ini seemed to have the same affect as versions 12.11 and 12.10, which is to center both the part and sliced part in the Normal mode window.

The Project Planner window seems to take the machine_depth and machine_width values and divide them by two for its centering.

Thanks for the leads in figuring this out. I look forward to trying this out on my printer this evening, instead of through a gcode viewer.

Without object_center_\* values:
![image](https://f.cloud.github.com/assets/2300403/34525/b2de7170-5125-11e2-8eb6-e4130b0936dd.png)

With manually entered object_center_\* values (70,75 in my case):
![image](https://f.cloud.github.com/assets/2300403/34528/db214892-5125-11e2-9298-9e7feaffb147.png)

**Comment by Intrinsically-Sublime** [comment]
@Chowderhead  it looks like Itchetiky found the issue you are having. You will need to set object center to 0.01 as well or it will put the object at half of the machines dimensions.

**Comment by Itchetiky** [comment]
@Intrinsically-Sublime @Chowderhead @AnthonyVH

Things are working great on the printer, though it did take a bit more tweaking in the start.gcode area. This of course falls into the YMMV realm..

I commented out the following lines as they seemed to keep my gcode changes from working:

```
;G28 X0 Y0  ;move X/Y to min endstops
;G28 Z0     ;move Z to min endstops
;G92 X0 Y0 Z0 E0         ;reset software position to front/left/z=0.0
```

Instead of the two sets of G28's I used a single G28 by itself on a line.

I must've missed a check box somewhere to have the bed heater turn on so I put in my own.

I do like the print head raising, or bed lowering depending on your point of view, but I have a problem with it coming back down so I force it back down.

So far the print is placed in the area of the print bed I was expecting and the code is working great.

Here's my complete start.gcode stanza:

```
M190 S65 ; wait for bed temperature to be reached
;Sliced {filename} at: {day} {date} {time}
;Basic settings: Layer height: {layer_height} Walls: {wall_thickness} Fill: {fill_density}
;Print time: {print_time}
;Filament used: {filament_amount}m {filament_weight}g
;Filament cost: {filament_cost}
G21        ;metric values
G90        ;absolute positioning
M107       ;start with the fan off
;G28 X0 Y0  ;move X/Y to min endstops
;G28 Z0     ;move Z to min endstops
;G92 X0 Y0 Z0 E0         ;reset software position to front/left/z=0.0
G28
G1 Z15.0 F{max_z_speed} ;move the platform down 15mm
G1 X{object_center_x} Y{object_center_x} F{travel_speed}
G92 E0                  ;zero the extruded length
G1 F200 E3              ;extrude 3mm of feed stock
G92 E0                  ;zero the extruded length again
G1 Z0 F{travel_speed}
G1 F{travel_speed}
G1 Z0
```

Like I said, I really dig Cura now.

Thank you Daid and Others.

**Comment by ghost** [comment]
Changing object_center_\* = 0.1 did the trick, Itchetiky. Thanks for that.

Agreed, Cura rocks. The tool path is absolutely sane and print quality is outstanding. An excellent product and greatly appreciated!

**Comment by daid** [comment]
(You people do know the toolpath is still generated with good old Skeinforge? People have called it much less then sane in the past :P)

**Comment by ghost** [comment]
Daid - that's cool by me. The only thing insane about Skeinforge (in my
opinion) is the number of buttons...

**Comment by Intrinsically-Sublime** [comment]
@daid when you compare SF path with comb enabled to a path generated by Slic3r or Kisslicer it seems like a miracle.

**Comment by Intrinsically-Sublime** [comment]
Also could you not change the math to be <= 0 for bed center and object center to avoid the requirement of the fudged decimal number needed to have zero center (since the default is -1)? Then add a button to the preferences that says "Center at zero" (Required for Rostock) that sets the bed and object center to 0 if selected.

**Comment by daid** [comment]
I'm thinking about adding a Rostock option so solve this for the RoStock. I'm not even sure why the "setting object_center_x/y" works at all. But it's a workaround that's not part of the design ;-)

**Comment by lazerusrm** [comment]
Thanks daid. my rostock max thanks u. :)

**Comment by ghost** [comment]
I can send a working Rostock profile if that's of use...

**Comment by shiverca** [comment]
Really? That would be awesome!!! I'm dying to try it as I'm wasting so much plastic with slicer and never satisfied with the results. Can you PM here?

**Comment by ghost** [comment]
https://github.com/Chowderhead/rostock/blob/master/Cura%20PLA%20profile

**Comment by shiverca** [comment]
Thank you sir!  I tried copying and replacing part it in a file that had similar parameters but didn't work.

I'm a noob, what's the easiest way to use it?
thank you

**Comment by daid** [comment]
As far as I know all bed center 0,0 issues have been solved now.
