### ISSUE TITLE
Set center of build platform or move part

### ISSUE THREAD

**Issue by Drachenkaetzchen** [daid/LegacyCura#310]
In cura 12.08, there was an option to set the center of the build platform - great to print the part in other positions than in the middle. 

However, this seems to be gone with 12.12 - can we have that back, or any other way to move a part?

**Comment by daid** [comment]
See: http://forum.ultimaker.com/viewtopic.php?f=8&t=2275&start=15

**Comment by EFinley** [comment]
I also just pushed a plugin which I wrote to do this directly within Cura's current version.  Daid will have to okay it into the primary before it can become standard issue (if that's how he wants to resolve this), but you should be able to grab it from /Cura/plugins directly here on Git.

Did it using actual changes to the X/Y/Z values instead of G92 set-origins stuff for reasons having to do with how I'm using it on my end.

**Comment by EFinley** [comment]
Per Daid's suggestion, moved from Git to the UM wiki page; you can get it at its shiny new [wiki page](http://wiki.ultimaker.com/CuraPlugin:_XYZshift).

**Comment by varalgit** [comment]
I second the question of timoahummel, it would be nice to be able to position the model without the need to hack the code...

**Comment by Drachenkaetzchen** [comment]
In my optinion, it's not something a plugin should do. It's already possible to rotate the model, even graphically, why not let the user move it?

**Comment by daid** [comment]
What's wrong with printing at the center?

**Comment by Drachenkaetzchen** [comment]
- Damaged blue tape in the center, but plenty of it at the outer edges
- Print in the upper right corner to reduce friction in the bowden tube

Any probably some more use cases I've forgotten. I really used the positioning feature quite often, so I instantly noticed it was missing when upgrading.

**Comment by EFinley** [comment]
My main use case is to print one object, /not/ remove it from the tape, 
and then print some other object (or perform other GCode operations 
equivalent to printing) in the same coordinate system.  So even if I'm 
happy with placing the first object in the centre of the platform, the 
next one will depend on the placement of the first, often in a very 
critical way.

Whereas rotating the object and even scaling it... those are easily 
accomplished in creating the STL in the first place, and I find them 
almost completely useless in Cura.

Even if Cura had the option to simply use the origin of the STL file as 
the origin of the machine, I could work with that.  It's having no 
control at all that's the killer.

I concur that it shouldn't be a plugin - I wrote the plugin to allow me 
to work with it at all, right now, without having to revert to an 
earlier Cura.
- Eric

**Comment by daid** [comment]
Sounds like you manually try to do what the project planner is designed to do for you. (The rotation in Cura is something I'm working on)

**Comment by EFinley** [comment]
Not quite.  The project planner wouldn't let me, say, print a cone, then 
print a different object partway up one side of the cone (the new 
object's not starting at z=0, and it's not merely /not centered/ but /at 
specific coordinates/).

I need to be able to define those offsets with machine precision.

If the project planner allowed that, then it could work - but the 
project planner is still a psychological extra step.  Why put rotation 
and scaling and mirroring in the main one, but not translation?  It just 
doesn't make sense (as you're hearing from multiple people at this point).
- E

**Comment by daid** [comment]
Ease of use is why I removed it. Less is more. Any change that removes an option will be met with resistance. Translation X/Y is possible with the project planner manual placement (in the next version this will be available again). And our planning is to get rid of the separate "project planner" and "normal" view and always be in project planner type of view.

But printing above the bed at a specific Z, I've done that, just requires a minor adjustment in the start code. But the pauze-at-height plugin also works for most of those cases. Sounds like a perfect highly advanced use suited for a plugin.

**Comment by EFinley** [comment]
Whatever; doesn't matter to me.

I do have one suggestion, though - enabling something like shift-drag to 
do the X/Y translation could allow you to still have nonshift-drag move 
the camera viewpoint as it is now.  Just turn the "rotate ring" into an 
iconic arrows-pointing-in-+x/-x/+y/-y icon while shift is depressed; 
nice, intuitive UI.

Anyway, thank you, David, for all your hard work; I think the basic 
message of "hey, please don't remove that UI functionality for the sake 
of simplicity, we /use/ that!" has been communicated already.

Now back to driving syringes using the Bowden cable...
- E

**Comment by illuminarti** [comment]
With respect, I feel like ease of use is more about making sure that there are sensible defaults, and that less-used options are not cluttering the important things in the user interface, so that users don't have to  think about more obtuse options unless they really want to.  I agree that flat, level and centered on the bed are all great defaults. Most of the time, we shouldn't have to think about it.

But equally, object positioning is absolutely fundamental to the slicing process - it's something that you have to do already as part of the process, and it affects basically every line of the resulting gcode. Working around it to correct it after the fact is a pain, and very inefficient compared to just setting the coordinates explicitly on the front end.

So, I'd caution you not to totally remove core functionality that has any sort of plausible use case. The logical conclusion of a 'less is more' approach is to have a slicer tool with zero configuration options. You load the file, and it slices it, 'with sensible defaults'. Which is great once these are truly consumer appliances. But we aren't there yet. The 'simple' interface in Cura is already kinda doing that, and that's fine for that audience. But if you are going to have a more advanced UI as well, I don't see the gain in removing fundamental settings in the name of 'simplification' - especially things that are a pain to fix after the fact.

As I said previously on the google group, if Cura is supposed to be UM's idiot-proof one-size-fits-all consumer 3D-printer manager, thats great. But I think that should be explicitly stated as such, so that those of us that need a bit more can focus on the tools that we don't have to fight to get the features that are genuinely useful to us. 

Don't get me wrong, I'm grateful for Cura, and all the work that goes into it - especially pre-UM-sponsorship - and I think its a powerful and elegant solution. It's still my go-to tool for most uses. But its preceisely because I think it has so much potential, and because its the 'official' tool, that I feel like it should also be the best, purest, most powerful solution. As a someone with 30-years experience in UI design and development, I realize what a tall order that is, but I also believe that Daid and UM are up to that challenge. :-)
