### ISSUE TITLE
Bundling Skeinforge: Questions for Fedora Packaging Committee

### ISSUE THREAD

**Issue by hroncok** [daid/LegacyCura#335]
Hi,
me again about Fedora package. Even if you've said your Skeinforge is different, it is considered as bundling (which is prohibited in Fedora) and therefor I need to get an exception from Fedora Packaging Committee.

Before I can start, I need to answer following questions (from [here](https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries#Standard_questions)). It would be very helpful if you could help me with that. My notes ar written in _italics_.
- Has the library behaviour been modified?  If so, how has it been modified?  If the library has been modified in ways that change the API or behaviour then there may be a case for copying.  Note that fixing bugs is not grounds to copy. If the library has not been modified (ie: it can be used verbatim in the distro) there's little chance of an exception.
  - Why haven't the changes been pushed to the upstream library?  If no attempt has been made to push the changes upstream, we shouldn't be supporting people forking out of laziness.
  - <del>Have the changes been proposed to the Fedora package maintainer for the library?  In some cases it may make sense for our package to take the changes despite upstream not taking them (for instance, if upstream for the library is dead).</del> _Actually, that's me, so don't answer this question._
- Could we make the forked version the canonical version within Fedora?  For instance, if upstream for the library is dead, is the package we're working on that bundles willing to make their fork a library that others can link against?
  - _I don't think we could do that, I suppose you've modified vanilla Skeinforge, so it communicates with Cura and it is impossible to use it standalone, am I right?_
- Are the changes useful to consumers other than the bundling application?  If so why aren't we proposing that the library be released as a fork of the upstream library?
- Is upstream keeping the base library updated or are they continuously one or more versions behind the latest upstream release?
- What is the attitude of upstream towards bundling?  (Are they eager to remove the bundled version?  are they engaged with the upstream for the library?  Do they have a history of bundling?  Are they argumentative?)
- Overview of the security ramifications of bundling
- <del>Does the maintainer of the Fedora package of the library being bundled have any comments about this?</del> _Actually, that's me, so don't answer this question._
- Is there a plan for unbundling the library at a later time?  Include things like what features would need to be added to the upstream library, a timeline for when those features would be merged, how we're helping to meet those goals, etc.
- Please include any relevant documentation -- mailing list links, bug reports for upstream or the bundled library, etc.
  - _I would like to include link to this issue._

**Comment by daid** [comment]
Skeinforge is actually an application, not a library. Not sure if that makes a difference.

But it was copied for the following reasons:
- Large changes needed for better integration into my own code (removal of the old GUI code in the application)
- Bugfixes, because the original was hardly maintained at all, and contained numours bugs. Some bugs are reported here on github, others where fixed without an issue tracking. Others where reported to me personally on email or the Ultimaker forums.
- New features.
- Original maintained did not know, nor care to use source control.
- Why trying to submit patches to original maintainer you ran into a lot of resistance and got no attribution for fixes. Just getting fixes in was a lot of effort with little reward.

Right now it's an integrated part of Cura. Cura cannot live without Cura_SF nor can Cura_SF work without some parts of Cura.

However, our "future plan" is to replace Cura_SF completely with our own solution, answering the "unbundle" question. The rest can pretty much be answered with "not bundling it but using it as an important library was not worth the effort".

It might be better to see Cura as a fork of Skeinforge then as an application that uses skeinforge.

**Comment by hroncok** [comment]
Thanks a lot.

**Comment by hroncok** [comment]
In case you are interested: https://fedorahosted.org/fpc/ticket/244

**Comment by hroncok** [comment]
Cura was finally approved as a Fedora package. Thansk for your help.
