### ISSUE TITLE
Dependency check for power insufficient

### ISSUE THREAD

**Issue by jinnatar** [daid/LegacyCura#354]
The current check will accept any module called power and when installing with pip, you end up with this module: http://pypi.python.org/pypi/power/1.0.1 .. which passes the check but manifests as just not being able to print (as referenced in #155 ), without any errors.

Of course properly fixing this is out of scope for Cura and the correct power module needs to be renamed, but in the interim Cura could properly verify it has the right module and throw a helpful error for getting the right one.

**Comment by Kentzo** [comment]
Hi,

Requirements files already point to the repo directly. This module is pretty new and, to be honest, it's useless. I've created a ticket on [PyPI](https://sourceforge.net/tracker/?func=detail&aid=3603152&group_id=66150&atid=513504).
Hopefully I'll be able to upload my module soon to PyPI, since PyObjC was finally updated recently.

**Comment by Kentzo** [comment]
This module was removed from PyPI. I'm going to upload mine within 2 days.

**Comment by Kentzo** [comment]
Done. #355

**Comment by Kentzo** [comment]
I think you can close the issue now, since pull request is merged.
