### ISSUE TITLE
Calibrated steps per e incorrect after the initial setup

### ISSUE THREAD

**Issue by Steinbex** [daid/LegacyCura#36]
If you go back to fix the calibrated length, it seems that the system doesn't recalibrate from scratch, but rather does a relative adjustment assuming that you had started from the default value. This works fine for the initial cal, but if you change it later, it will result in terrible calibration. 

I am using Cura beta4, on 64bit windows 7. Also, I'd recommend adding a version check in help to make easier bug reporting. 
Truly awesome software, thanks very much

**Comment by daid** [comment]
I'm not sure what you think that's going wrong, because I see no error in the code. Maybe the instructions are not very clear.

The idea behind the "steps per E" calibration is that you do the following steps:
-Press the extrude 100mm button
-Measure your filament extrusion
-Enter that value
-Press the [save] button
And repeat these 4 steps.

**Comment by Steinbex** [comment]
Daid,

Sorry about that, it looks like I found a bug that isn't really a bug.
Basically wizard won't communicate with my machine so I've been just
running the 100m through pronterface and measuring from there. If you do
that you get horrible numbers after the initial calibration. I think the
real solution would be for me to fix that communication issue in my setup,
but a nice feature might be a button that allows the user to reset the
steps_per_e to default, and maybe a tooltip on the save button that would
mention this issue. If you don't have time I'd be happy to add it and send
you a pull request

On Fri, Apr 6, 2012 at 3:55 AM, daid <
reply@reply.github.com

> wrote:
> 
> I'm not sure what you think that's going wrong, because I see no error in
> the code. Maybe the instructions are not very clear.
> 
> The idea behind the "steps per E" calibration is that you do the following
> steps:
> -Press the extrude 100mm button
> -Measure your filament extrusion
> -Enter that value
> -Press the [save] button
> And repeat these 4 steps.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/daid/Cura/issues/36#issuecomment-4993144

## 

-Alex Steinberg

**Comment by daid** [comment]
No problem that you found a bug that isn't a bug ;-)

I think solving the communication errors would be better. The wizard is build around the fact that it can communicate with your machine. I also am thinking about changing the wizard to be less "do steps X,Y,Z" and more "do step X" "do step Y" "do step Z" for the calibration part. With some photos. Then you wouldn't have been able to use the wizard "wrongly" because you wouldn't have got past the extrude 100mm step.

You might want to try the RC1 release, this contains a few fixes on the serial interface that might help.

**Comment by frollard** [comment]
Greetings;

Might be having the same issue as a month ago; 
hit 'extrude' on the config, the wizard connects, the motors all energize...then nothing is extruded, several seconds later, the motors power back off.  Hitting save doesn't cause the 'extrude' button to come active again, cannot repeat, nothing ever comes out.
Cura RC1 Win7 -- I'm confident the value is not quite right because after a short time printing the machine tries to self destruct over-extruding.  I went back to use the wizard that used to work, and now does not.

**Comment by daid** [comment]
You you tell me with steps_per_e value the wizard is reporting at the start? Because this is the value used for the extrusion. If it's 0 then the calibration doesn't work because it fails to extrude.

**Comment by frollard** [comment]
Not sure why, after numerous restarts, it just started working - steps per e was in the 800 range.
