### ISSUE TITLE
unable to centre build platform in cura 12.12

### ISSUE THREAD

**Issue by boshy** [daid/LegacyCura#372]
I have been running cura 12.08 with no real problems.
changed to 12.12 and no longer have the ability to set the platform centre.
can this be reinstated please.

**Comment by greenarrow** [comment]
This is the relevant patch:
https://github.com/daid/Cura/commit/4c5ff7f275f34318cce717b44059bca5f8dcf64a

I presume the reasoning here was that having a user setting for platform centre is logically incorrect, as any given platform has one absolute centre.

**Comment by daid** [comment]
You are correct with your presumption. You can set the platform size, which influence the center.

**Comment by boshy** [comment]
As I have about a 70mm offset from my home position to the edge of my build platform I have to increase my platform size by 140mm to centre it . 
If it would be possible to define the platform centre as in cura 12.08 I would be very grateful.

**Comment by daid** [comment]
You could also fix it in your start code. By changing the G92

**Comment by boshy** [comment]
Yes I can change the Gcode but I belong to the connected community hackerspace in melbourne Australia and am constantly working on many different printers in one night plus I own 3 different types myself and it was just really convenient to do it in the software.
I can keep using 12.08 I suppose.
thanks for chatting about it .
For me a great feature lost.

**Comment by Alzibiff** [comment]
I downloaded the current version of CURA today but am having a problem using it with my RepRap which has the centre of the bed at x=0, y=0. The idea behind this scheme rather than having x=0, y=0 at one corner of the bed is so that I can slice and print on either of my two machines - one has a bed which is 140mm square and the other 200mm square. Would a previous version of CURA be better for me in this regard?

**Comment by daid** [comment]
There will be a 13.03 release later out today which has a setting for 0,0 bed center that delta bots also need.
