### ISSUE TITLE
M108 in start.gcode or end.gcode is stripped from output

### ISSUE THREAD

**Issue by kefir-** [daid/LegacyCura#378]
Some gcode is stripped from the start and end gcode when generating the output. For example. M108 in start.gcode or end.gcode is not in the output. This is probably Skeinforge's fault, because I've had the same issue with SFACT, but it's not reported in any way in Cura. A workaround would be useful.

**Comment by daid** [comment]
M108 is "set extruder RPM", which is forcefully stripped out at some part of the code. (After all, extruder RPM doesn't make sense in a step extruder world)

However, due to changes in 13.03 this will most likely no longer be an issue in the 13.03 release, at it uses a different method to insert the start/end GCodes.

**Comment by kefir-** [comment]
OK, thanks. On my MakerGear M2 with a slightly customized Marlin, M108 is used to set system fan speed.

**Comment by daid** [comment]
Most likely you could have abused M42 for the fan (as M42 is a huge possible abuse code :-) )

For a list of already used (and mostly depricated) codes: http://reprap.org/wiki/MCodeReference
(M108 is used a lot internally in Skeinforge)
