### ISSUE TITLE
Prepare fails with python file access exception on Ubuntu 12.10

### ISSUE THREAD

**Issue by phord** [daid/LegacyCura#382]
I get an exception when I try to prepare the sample robot.  It is trying to write the gcode to a directory where it does not have write permissions.  I do not see any way to change this directory, and there does not seem to be a way to "Save as" to change the location of the source example, either.

```
/usr/bin/python /usr/share/cura/cura.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/share/cura/Cura/gui/sliceProgressPanel.py", line 190, in run
    gcodefile = open(gcodeFilename, "a")
IOError: [Errno 13] Permission denied: u'/usr/share/cura/Cura/resources/example/UltimakerRobot_support.gcode'
```

I can work around this problem by copying the stl to a directory I do have rights to and preparing there.

**Comment by daid** [comment]
Odd, it should have copied the example files, most likely something is amiss for the condition of doing this (as I've seen it fail on MacOS too)

**Comment by plasmasolutions** [comment]
Hi daid,
I could be wrong, but this issue is most likely because you can't append your data to the file! You don't have any write access to /usr/share/cura/Cura/resources/example/UltimakerRobot_support.gcode... so you'll get the error!
I experience the same error and am sure that it is like that.

Apart of that, I've got several errors on ubuntu 64 12.10...will dig into it to help you!
