### ISSUE TITLE
E values appear VERY large

### ISSUE THREAD

**Issue by Alzibiff** [daid/LegacyCura#385]
Comparing the GCode output of CURA V13.03 with Skeinforge files which I sliced before and which have printed successfully, the values of the extruder travel seem extremely high which explains the massive deposit of PLA on my print bed and rapid turning of the extruder motor  causing me to switch off at the mains in order to bring my RepRap to a halt immediately.
The following 3 lines come from a GCode file from Skeinforge:
G1 X-23.495 Y3.993 Z0.2 F750.0 E0.0374
G1 X-23.023 Y6.182 Z0.2 F750.0 E0.0208
G1 X-21.666 Y9.926 Z0.2 F750.0 E0.0369

The CURA output for something similar is:
G1 X-24.083 Y6.154 Z0.3 F1200.0 E1.6506
G1 X-22.643 Y10.303 E1.732
G1 X-21.264 Y12.951 E1.7874

Can you help me to identify which settings I need to change - I have spent ages looking for where I am going wrong but as you can see, the E travel is massive in CURA compared to my previous GCode files. (I HAVE checked the M92 value in preferences and set these to match my extruder steps/mm).
Alan

**Comment by illuminarti** [comment]
The major reason the numbers look so different is that Cura is using absolute E values.... counting its way along the filament, so the counter goes up each time. Those are not absolute amounts to extrude on each line, but how far to advance to... the difference in the numbers is what matters each time. Whereas, the original SF code is in relative E values - it _IS_ the amount to extrude each time - notice that the number goes up and down at each step.

Depending on your firmware and printer, either might work. With Marlin firmware, you can use an M82 in your start gcode to force it to use absolute E values. Possibly your existing gcode has an M83 earlier on, telling it to use relative E amounts? Or it defaults to that behavior. Or maybe your firmware/printer ONLY supports relative E amounts. I don't know the specifics of your printer, or much about non-Ultimakers printers running Marlin (and they can work either way).

Furthermore, running the math on the numbers, it looks like the Cura outputs are correct for on a 0.3mm layer height, with a nozzle width of 0.4mm and filament width close to 2.88mm. The SF numbers on the other hand are 'right' for a 0.3mm nozzle at 0.2mm layer height, with the same size filament. So maybe the issue is not the relative/absolute E values at all (maybe your printer is handling that ok after all) but rather than you have Cura configured for a 0.4mm nozzle, rather than 0.3mm? That would give you nearly twice as much plastic per second as you are used to... on the other hand, the relative/absolute difference (if your printer can't handle it) would give you 50 or 100 times more plastic than you are want. I get the impression it's the latter from your comments.

That said, I don't know of a simple way to make Cura generate relative E values (... unless the first run wizard has some smarts, Daid?) What firmware are you using?  If your firmware understands it, you could be sure to add an 'M82' to the start gcode block (or remove any M83's that have the opposite effect), in order to force it to recognize the E values as absolute measures, not relative ones. (And then make sure you set the right nozzle width and layer height that you want).

**Comment by Alzibiff** [comment]
What you say makes a lot of sense - thank you. I am running MARLIN and relative values as you worked out! Indeed - my start GCode includes an M83! I will start experimenting ..... (but for RepRaps I think that it would be nice to have the choice of relative/absolute extruder values).
Thanks again,
Alan

**Comment by Alzibiff** [comment]
For anyone with the same problem, I navigated to a file in the CURA directory called settings.py and amended the Relative and Absolute Extrusion values to TRUE and FALSE respectively with a text editor - I have not had chance to try the GCODE out yet but it certainly looks like what I expected it to look like.

A knock on effect - and I cannot immediately see a reason for this - is that the CURA display at the end of the slicing operation now also looks as I expected it. Before, I was getting a screen full of colours rather than a screen just showing my object in colour. It is as if CURA knew that I was set up to use relative extrusion by default somehow - the mass of colour representing the stack of extruded filament which I was getting. Having made the changes which you suggested, I can use all of the display options as described in the Ultimaker Screencast.

**Comment by daid** [comment]
Note that relative E values with Skeinforge are a bad idea, as Skeindog does some horrible rounding stuff, which adds ups, combined with slight rounding errors in the firmware. So absolute E values give a better printing result.

**Comment by Intrinsically-Sublime** [comment]
I would put money on that being false. PLEASE post pictures of such a result. It's an old wives tale that has zero posted proof I have ever been able to find.

**Comment by daid** [comment]
How much money?

**Comment by Intrinsically-Sublime** [comment]
I would actually really like to see some kind of proof that a problem exists other than in theory because in theory carrying over the rounding will not result in more precise extrusion but rather less precise. What I mean is if any amount that could be dropped is enough to cause an issue than it is enough to cause an issue if added to the next extrusion causing an over extrusion issue. When it comes down to making parts that fit together you would rather have a slight under extrusion then an over extrusion that would not allow parts to fit together. All the mentions of relative extrusion being a problem that I can find on Google are either theoretical or warnings from people but never any proof or citations they are basing there claims on.
