### ISSUE TITLE
Error message: 'Attempt to retrieve context when no valid context' in Cura 13.03

### ISSUE THREAD

**Issue by PabloBell** [daid/LegacyCura#393]
![Error](https://f.cloud.github.com/assets/4010404/319793/9974eba8-98e5-11e2-83f4-03565d683b01.png)
When I close that window, I can slice and generate gcode perfectly, but the the 3D view is blank (white). And when the main window is resized the updated surface in the 3D view is filled with grey. The same thing happened to me with Cura 12.
I have windows 7 and Python 3.3 x64 installed. My graphics card is an old ATI Radeon HD 4850, with latest driver updates.

**Comment by daid** [comment]
Somehow, on some ATI Radeon cards, the OpenGL window generation fails. I haven't been able to track it down yet. But the problem has been reported before (which is why I added the popup, which allows me to track it down a bit better, as there is another issue which also results in the gray window in a different way)

This could be because I specifically ask 24bit depth buffer and an 8 bit stencil buffer. And I just found out that a 24bit depth buffer is "none standard" (usually 16 or 32 bit is used). I currently do not have a version that uses a different depth buffer size, but if you are willing to hack a file then we could do some tests.

(I assume you have DirectX installed, as I think this sometimes also affects the wxPython OpenGL implementation)

**Comment by PabloBell** [comment]
I don't know what you mean by 'hack a file'. My programming skills are almost non-existent so I'm afraid I could not alter any Python or Cura source code. But if you provide me with a modified file, I would gladly compile the code and try it!

**Comment by PabloBell** [comment]
Sorry, this github interface is new to me :)
And also, I meant that I could do some testing if it's not too complicated and you guide me a bit through it.

**Comment by daid** [comment]
No problem. It shouldn't be too hard to test a few things. Changing the python code is quite easy (it's all just text files). But I'll send you some new files you can just copy over the old ones to test a few things.

**Comment by PabloBell** [comment]
ok.

**Comment by dev0001** [comment]
Hi,
I am also having the same problem. Since this issue still not resolved, does anyone know a workaround by changing the python code? Not even sure which file this is in.
Thanks

**Comment by daid** [comment]
I've yet to find a cause. There is very little code ran related to the OpenGL context (which is the part that is failing) before this error.

If you want to test things, you should look at /Cura/Cura/gui/util/openglGui.py, around line 100 there is:

```
attribList = (glcanvas.WX_GL_RGBA, glcanvas.WX_GL_DOUBLEBUFFER, glcanvas.WX_GL_DEPTH_SIZE, 24, glcanvas.WX_GL_STENCIL_SIZE, 8)
```

This is pretty much the only initialization that is done that is related to the context.

**Comment by nhfoley** [comment]
I'm now having this issue. It is certainly related to DirectX, as it was working until I installed AutoDesk DWG TrueView, which installed (updated? I'm on 64bit Windows 7) DirectX 11 along with it. Uninstalling TrueView has not solved the problem.

I went in to the Python and set the buffer to 16 and 32 bits, neither seemed to have any effect. 

Any other suggestions? Could I possibly get back to having a working Cura by reinstalling python? Reinstalling Cura alone didn't make a difference.

**Comment by daid** [comment]
I tried installing AutoDesk DWG TrueView, but it did not install DirectX. I also tried downloading DirectX from Microsoft directly, but it says it is already installed the latest version.
Have you tried installing the latest DirectX straight from Microsoft?

**Comment by nhfoley** [comment]
Ehhh, yeah, the DirectX install process is a strange thing. I guess more correctly it installed a specific version of DirectX? (9? 10? 11?....) I'm not entirely sure which, though, as it didn't pay attention to the number during the install, and of course it doesn't say anything about the version of DirectX in the Trueview system requirements.

I tried updating DirectX from Microsoft to no result - it says that a newer or equivalent version of DirectX is already installed.

**Comment by daid** [comment]
Yeah, DirectX is a piece of... fecal matter.

I think the only way to see your current version is by running "dxdiag", and there are no options to uninstall, reinstall or downgrade DirectX. But maybe installing newer video-card drivers helps...

**Comment by nhfoley** [comment]
Yeah. I reinstalled my graphics drivers last night, but unfortunately since I'm using a laptop I'm restricted the the drivers coming through Samsung first.

Here's some of the more relevant sections of dxdiag:

---

## System Information

Time of this report: 6/7/2013, 09:11:24
       Machine name: NHFOLEY-PC
   Operating System: Windows 7 Home Premium 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.130318-1533)
           Language: English (Regional Setting: English)
System Manufacturer: SAMSUNG ELECTRONICS CO., LTD.
       System Model: 700Z3A/700Z4A/700Z5A/700Z5B
               BIOS: Phoenix SecureCore-Tiano(tm) NB Version 2.1 15FD
          Processor: Intel(R) Core(TM) i7-2675QM CPU @ 2.20GHz (8 CPUs), ~2.2GHz
             Memory: 8192MB RAM
Available OS Memory: 8106MB RAM
          Page File: 4724MB used, 11485MB available
        Windows Dir: C:\windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 64bit Unicode

---

## DxDiag Notes

```
  Display Tab 1: No problems found.
    Sound Tab 1: No problems found.
      Input Tab: No problems found.
```

---

## DirectX Debug Levels

Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

Name: AMD Radeon HD 6490M
Device ID: PCI\VEN_1002&DEV_6760&SUBSYS_C0B3144D&REV_00\4&35D5CDB7&0&0008
   Driver: C:\windows\system32\DRIVERS\atikmdag.sys, 8.01.0001.1223 (English), 12/5/2011 22:45:42, 10720256 bytes
   Driver: C:\windows\system32\DRIVERS\ati2erec.dll, 1.00.0000.0023 (English), 12/5/2011 21:10:26, 53248 bytes
   Driver: C:\windows\system32\DRIVERS\atikmpag.sys, 8.14.0001.6248 (English), 12/5/2011 21:12:16, 327168 bytes
   Driver: C:\windows\system32\atiumd64.dll, 7.14.0010.0887 (English), 12/5/2011 21:24:04, 7511040 bytes
   Driver: C:\windows\system32\atiumd6a.dll, 8.14.0010.0342 (English), 12/5/2011 21:39:14, 4072960 bytes
   Driver: C:\windows\system32\atitmm64.dll, 6.14.0011.0023 (English), 12/5/2011 22:10:40, 120320 bytes
   Driver: C:\windows\system32\atiicdxx.dat, 11/14/2011 14:47:24, 608507 bytes
   Driver: C:\windows\system32\amdpcom64.dll, 8.14.0010.0023 (English), 12/5/2011 21:10:50, 54784 bytes
   Driver: C:\windows\system32\atimpc64.dll, 8.14.0010.0023 (English), 12/5/2011 21:10:50, 54784 bytes
   Driver: C:\windows\system32\atiadlxx.dll, 6.14.0010.1089 (English), 12/5/2011 21:13:04, 509952 bytes
   Driver: C:\windows\system32\atiumd6a.cap, 12/5/2011 21:35:12, 2095328 bytes
   Driver: C:\windows\system32\atimuixx.dll, 6.14.0010.1002 (English), 12/5/2011 22:09:58, 21504 bytes
   Driver: C:\windows\system32\atiapfxx.exe, 6.14.0010.1001 (English), 12/5/2011 22:17:52, 159744 bytes
   Driver: C:\windows\system32\atiapfxx.blb, 12/5/2011 22:18:30, 219080 bytes
   Driver: C:\windows\system32\atiumd6v.dll, 7.14.0010.0184 (English), 12/5/2011 21:40:00, 1113088 bytes
   Driver: C:\windows\system32\ativvsva.dat, 12/5/2011 21:35:12, 157152 bytes
   Driver: C:\windows\system32\ativvsvl.dat, 12/5/2011 21:35:12, 204960 bytes
   Driver: C:\windows\system32\atiesrxx.exe, 6.14.0011.1114 (English), 12/5/2011 22:11:58, 235520 bytes
   Driver: C:\windows\system32\atieclxx.exe, 6.14.0011.1114 (English), 12/5/2011 22:12:38, 494080 bytes
   Driver: C:\windows\system32\atipdl64.dll, 6.14.0010.2563 (English), 12/5/2011 22:10:22, 423424 bytes
   Driver: C:\windows\system32\atiedu64.dll, 6.14.0010.2514 (English), 12/5/2011 22:09:52, 59392 bytes
   Driver: C:\windows\system32\ATIDEMGX.dll, 2.00.4356.39985 (English), 12/5/2011 22:12:52, 466944 bytes
   Driver: C:\windows\system32\atio6axx.dll, 6.14.0010.11399 (English), 12/5/2011 22:18:40, 25371136 bytes
   Driver: C:\windows\system32\aticaldd64.dll, 6.14.0010.1664 (English), 12/5/2011 21:34:02, 13738496 bytes
   Driver: C:\windows\system32\aticalrt64.dll, 6.14.0010.1664 (English), 12/5/2011 21:34:30, 51200 bytes
   Driver: C:\windows\system32\aticalcl64.dll, 6.14.0010.1664 (English), 12/5/2011 21:34:18, 44544 bytes
   Driver: C:\windows\system32\atipblag.dat, 9/12/2011 21:06:18, 3917 bytes
   Driver: C:\windows\system32\atiu9p64.dll, 8.14.0001.6248 (English), 12/5/2011 21:11:12, 39936 bytes
   Driver: C:\windows\system32\atiuxp64.dll, 8.14.0001.6248 (English), 12/5/2011 21:11:26, 42496 bytes
   Driver: C:\windows\system32\atig6pxx.dll, 8.14.0001.6248 (English), 12/5/2011 21:12:40, 17408 bytes
   Driver: C:\windows\system32\atig6txx.dll, 8.14.0001.6248 (English), 12/5/2011 21:12:32, 39936 bytes
   Driver: C:\windows\system32\atibtmon.exe, 2.00.0000.0000 (English), 5/11/2009 16:35:30, 118784 bytes
   Driver: C:\windows\system32\atidxx64.dll, 8.17.0010.0414 (English), 12/5/2011 21:51:24, 7520768 bytes
   Driver: C:\windows\SysWOW64\atiumdag.dll, 7.14.0010.0887 (English), 12/5/2011 21:33:38, 5919232 bytes
   Driver: C:\windows\SysWOW64\atiumdva.dll, 8.14.0010.0342 (English), 12/5/2011 21:28:52, 4206592 bytes
   Driver: C:\windows\SysWOW64\amdpcom32.dll, 8.14.0010.0023 (English), 12/5/2011 21:10:44, 53760 bytes
   Driver: C:\windows\SysWOW64\atimpc32.dll, 8.14.0010.0023 (English), 12/5/2011 21:10:44, 53760 bytes
   Driver: C:\windows\SysWOW64\atiadlxy.dll, 6.14.0010.1089 (English), 12/5/2011 21:12:54, 356352 bytes
   Driver: C:\windows\SysWOW64\atiumdva.cap, 12/5/2011 21:27:38, 2097056 bytes
   Driver: C:\windows\SysWOW64\atiumdmv.dll, 7.14.0010.0184 (English), 12/5/2011 21:39:26, 1828864 bytes
   Driver: C:\windows\SysWOW64\atiapfxx.blb, 12/5/2011 22:18:30, 219080 bytes
   Driver: C:\windows\SysWOW64\ativvsva.dat, 12/5/2011 21:35:12, 157152 bytes
   Driver: C:\windows\SysWOW64\ativvsvl.dat, 12/5/2011 21:35:12, 204960 bytes
   Driver: C:\windows\SysWOW64\atipdlxx.dll, 6.14.0010.2563 (English), 12/5/2011 22:10:14, 360448 bytes
   Driver: C:\windows\SysWOW64\Oemdspif.dll, 6.15.0006.0006 (English), 12/5/2011 22:10:02, 278528 bytes
   Driver: C:\windows\SysWOW64\ati2edxx.dll, 6.14.0010.2514 (English), 12/5/2011 22:09:46, 43520 bytes
   Driver: C:\windows\SysWOW64\atioglxx.dll, 6.14.0010.11399 (English), 12/5/2011 21:56:42, 19125760 bytes
   Driver: C:\windows\SysWOW64\atidxx32.dll, 8.17.0010.0414 (English), 12/5/2011 22:06:40, 6159872 bytes
   Driver: C:\windows\SysWOW64\aticaldd.dll, 6.14.0010.1664 (English), 12/5/2011 21:29:32, 11484672 bytes
   Driver: C:\windows\SysWOW64\aticalrt.dll, 6.14.0010.1664 (English), 12/5/2011 21:34:26, 46080 bytes
   Driver: C:\windows\SysWOW64\aticalcl.dll, 6.14.0010.1664 (English), 12/5/2011 21:34:16, 44032 bytes
   Driver: C:\windows\SysWOW64\atipblag.dat, 9/12/2011 21:06:18, 3917 bytes
   Driver: C:\windows\SysWOW64\atiu9pag.dll, 8.14.0001.6248 (English), 12/5/2011 21:11:04, 29696 bytes
   Driver: C:\windows\SysWOW64\atiuxpag.dll, 8.14.0001.6248 (English), 12/5/2011 21:11:18, 33280 bytes
   Driver: C:\windows\SysWOW64\atigktxx.dll, 8.14.0001.6248 (English), 12/5/2011 21:12:24, 33280 bytes
   Driver: C:\windows\SysWOW64\atiglpxx.dll, 8.14.0001.6248 (English), 12/5/2011 21:12:36, 14336 bytes
   Driver: C:\windows\atiogl.xml, 10/10/2011 12:51:12, 36338 bytes
   Driver: C:\windows\system32\aticfx64.dll, 8.17.0010.1114 (English), 12/5/2011 22:16:02, 933888 bytes
   Driver: C:\windows\SysWOW64\aticfx32.dll, 8.17.0010.1114 (English), 12/5/2011 22:17:38, 778752 bytes
   Driver: C:\windows\system32\coinst.dll, 1.00.0003.0005 (English), 12/5/2011 21:18:46, 58880 bytes

**Comment by daid** [comment]
I think all problems related to this 3D rendering are solved now. Thanks to some testers.
