### ISSUE TITLE
Crumbly interior: infill every n layers

### ISSUE THREAD

**Issue by JelleB** [daid/LegacyCura#405]
When printing lower layer sizes like 0.1mm and below, you also get infill printed at 0.1mm layer height (infill as in the material inside the object, not up or down skins). This leads to crumbly interiors as each line gets too little material if there is no wall below it. Switching to a system like Slic3r's infill every n layers will reduce the time needed to print and reduce faults like the crumbly interior. Care should be taken to make sure that upskins always have the support they need on the layer below

**Comment by daid** [comment]
And a pony!

**Comment by GregFrost** [comment]
And a pony? Does that mean this is quite difficult to implement? There are two other related problems that printing with very thin layers causes. When you finally get to the top layers, the layers are so thin that the filament is stretched too much when it attempts to do the first solid layer and it just snaps rather than bridging the gap. This makes it almost impossible to use really thin layers except when printing solid objects.

The other place where the thin layers fall down is when attempting to do a bridge. Some other slicers have a bridge flow rate (or calculate one based on the nozzle size) because you can't use the normal flow math for bridges at arbitrary slicing height and expect them to work. They will either sag if the flow rate is too high, or more likely just snap the filament if the flow rate is too low. In either case, the bridge does not actually work properly.

So 3 things are needed: 
1. Infill every n layers as per the original request.
2. A bridge flow rate that you can tune for the characteristics of your nozzle and plastic.
3. When bridging over infill gaps, use the bridge flow rate.

**Comment by nophead** [comment]
As Cura seems to like keeping the flow rate constant for better quality perhaps it should be bridge feed rate that changes. Although it would then slow down on bridges which might make them sag more.

**Comment by GregFrost** [comment]
I think that would work fine. If the bridge is sagging, you have chosen a speed that is too slow. However, for very fine layers, the bridge speed might need to be very slow. You would also need to have a layer height dependent bridge speed unless you specified the speed in volume/mm or something (for a fixed volume/second determined by the layer height). Chris: I saw you commented on a blog somewhere that nut traps come out too small in cura because it doesn't take into account the rounded edges of the extrudate. Is that still the case? I searched for a ticket on that issue, but could not find one.
