### ISSUE TITLE
Woah! Bring back the Infill Pattern choices!

### ISSUE THREAD

**Issue by PaulDutch** [daid/LegacyCura#463]
It seems that in Cura 13.xx the choice between different Infill Patterns has been deleted.
Is this coming back in the near future??

**Comment by daid** [comment]
Yes, there will be different patterns.
I gave a huge presentation of 45 minutes on this new release. It explains a few things and it also answers the question on infill patterns.
http://blog.ultimaker.com/2013/06/24/ulti-evening-first-part-david-braam-on-cura/

**Comment by PaulDutch** [comment]
Wah? No executive summary for us busy bodies?
Kidding.. Thanks for your great work Daid!

Paul

**Comment by daid** [comment]
That's the summary, the full version is 2 months long ;-)

**Comment by PaulDutch** [comment]
Haha! Good one!

**Comment by OhmEye** [comment]
It's more than a year later, I updated my old Cura to 14.07 and discovered Infill Pattern selection has been removed, found this issue with a dead link to a blog that supposedly answers/explains it. The blog entry appears to not exist on blog.ultimaker.com, searching youtube did not find a video, can somebody please provide an answer to this issue for those of us who did not see the blog post before it disappeared?

**Comment by nallath** [comment]
Basicly; We ditched skeinforge as it was too slow. Daid made a whole new slicing engine from scratch, but it doesn't have all the functions of skeinforge yet.

**Comment by daid** [comment]
Pretty much the only infill structure supported right now is the grid/line infill. I have no plans anymore to bring any of the other infills back, as nobody managed to prove to me that the other infill structures provided a benefit except for aesthetic reasons. (And I have limited time, and rather work in improving external support structures and dual-extrusion for example)

Hex infill is usually talked about as "stronger", but I had a long discussion with someone who has way more knowledge about structural strength then I do, and we concluded that hex would be stronger in theory, but most likely not in practice due to the corners not being properly bonded, causing major weakness at those points. Line/grid is also much quicker to print and in pure theory not that much weaker.

**Comment by OhmEye** [comment]
Thanks for the responses. As far as I know there is no longer ANY selection of infill pattern, I don't see a choice between grid and line for infill, only support. However, I do have to disagree that hex is not stronger in practice, the percentage of pattern interlayer contact has a huge effect on overall layer cohesion strength. Most of my tests were done years ago with skeinforge but it was very clear that splitting/breaking/pulling apart test objects along layers (sometimes called delaminating) required significantly less force when infill patterns are used that only bond layers at line intersections.

There are different implementations of patterns. Skeinforge had a rectilinear one that was pathed as connecting stair steps, alternating 90 degrees each layer, which resulted in nearly 100% pattern contact between layers and was very strong and formed solid wall square vertical columns. Square patterns that simply do straight lines alternating angle each layer only have contact between the layers at the line intersections, which for low density infill is often less than 5% pattern contact between layers. Splitting test objects with such different percentages of bonded layer contact can require significantly different amounts of force.

Another way to express how the percentage of layer contact affects strength is to think in terms of volume efficiency. For a solid object, which has 100% contact between layers and is as strong as it gets. We can reduce the strength by reducing the amount of layer contact, with the goal of having high strength efficiency per layer volume. The contact between layers can be more or less efficient in terms of volume to layer contact. The more layer contact per volume of plastic, the higher the strength efficiency. By using a pattern that has very low contact for it's volume, efficiency is low, which means to achieve a given strength the volume must be increased by increasing infill density. It's good to have pattern options that maximize contact area per plastic volume. More strength, less plastic, higher efficiency.

I have been printing structural parts for commercial products for the past year that have continued to prove to me that hex style infill patterns can be much stronger in practice than equivalent density rectilinear or line patterns. I'm talking both intentional break testing and real-world customer feedback and support, cases where failure rate using rectilinear have a higher failure rate than hex in apples-apples comparison. (Same plastic, same printers etc.) Also, anybody who has ever tried hex for a support material pattern and compared to a line pattern should find it easy to confirm that there is a significant difference in strength between the two. It's very real. :)

Aesthetics can be important also, but I recognize it's a minority case since it usually only applies to transluscent plastics or artwork.

Please reconsider implementing some more pattern choices, at least something with a much higher percentage of contact between layers. Square, Triangular, Hex, or whatever, but something that forms solid vertical columns and doesn't just contact adjacent layers at straight line intersections. One of the main reasons I have used cura in the past is for some of the skeinforge features that have been missing from more recent slicer apps, I find it a shame to see features being removed and discouraging to see what I consider incorrect assertions that increasing the pattern contact between layers does not increase strength. I use several different slicing apps since no single one is ideal for all objects. For me, using cura is an option for fewer objects now than it was before.

**Comment by daid** [comment]
Cura switches between lines and grid depending on the infill percentage. (below 25% it does grid, else it does line) Which has to do with the fact that the grid over-extrudes a bit on the cross-sections, which isn't a problem on low densities, but a bigger problem on high density.

Note that the lines (high density Cura infill) is a bit the same as the rectilinear skeinforge infill. While the grid is done that at 45 and 135 degree angles every layer to solve the bonding problem.

As we explained, the feature didn't get scrapped, whole skeinforge got scrapped. For multiple reasons. And, there are no plans to bring this back (by me, contributors are free to do so)

**Comment by wgbartley** [comment]
@daid - That's good info on the 25% split.  I've been getting poor quality on my top surface layers because the gaps in the grid were too wide.  I bumped the infill up from the default 20% to 30% and top surfaces got much better.  Now that I know about the 25% infill grid/line split, I can reduce the amount of infill and retain the better top surface quality!  Thanks!

**Comment by dandroid88** [comment]
Has this feature been added back in.  I couldn't find any settings other than infill overlap % which only partially helps me make stronger parts.

**Comment by mario-chirinos** [comment]
I really would like to be able to choose other types of lattice structure (infill) .
I leave here something for all of you to read.
http://www.srl.gatech.edu/publications/2006/LatticeAnl_DWR_RM2006.pdf
http://erudiold.insa-lyon.fr/sites/default/files/rrinaldi/files/hammetter2013_j-app-mech_041015-1-11.pdf

**Comment by nallath** [comment]
Nice papers, thanks :)

**Comment by BagelOrb** [comment]
Lattice infill structures will soon be possible, but you will need to design them yourself and include the internal structure as separate STL.

For Cura to generate them will probably not be on the TODO list for the coming year to say the least.
