### ISSUE TITLE
store to sd

### ISSUE THREAD

**Issue by bkubicek** [daid/LegacyCura#486]
in cura 13.06_2 (curaengine) the slicing takes much much longer when storing to SD card. I think it would be in total quicker to write to a temporary directory, and then copy the file with an explorer like window to the card at once.
Maybe small incremental is the reason for the slow process.
tested on windows7_x64.

**Comment by daid** [comment]
Total time will be the same or slower. Cura (with GUI) writes the GCode first at a temp location, and then when you save it to SD card, it copies it. So it already does what you are suggesting. If you are using the engine directly, you could be slicing slower because it's streaming GCode to SD card, but in the end it's doing buffered writes, so it should take just as long as a slice&copy.
