### ISSUE TITLE
PVA not possible

### ISSUE THREAD

**Issue by farrellt** [daid/LegacyCura#490]
Attempting to use PVA 3mm filament (water soluble), the extruder motor wont work under 180 degrees and the recommended temperature is between 160-170. 180 actually burns it, causes it to come out black and in a weird consistency. Please ad a PVA temperature option

**Comment by ErikDeBruijn** [comment]
Hi Farrellt,

Using non-standard material puts you in the advanced/adventurous group of people :)

You 'should' be able to use any temperature when you're in the advanced mode:
![screen shot 2013-07-05 at 1 30 28 pm](https://f.cloud.github.com/assets/191236/753375/50c96d16-e566-11e2-9692-5be57b590b82.png)

Also, with the UltiController, you can adjust the temperature whenever you want to. Of course in this case you'll want to do it through Cura, because it could otherwise be charred before you have the time to adjust.

**Comment by daid** [comment]
This is an firmware issue, not directly a Cura issue. (As the firmware limits extrusions to temperatures above 170C)

**Comment by daid** [comment]
Oh, and you can add an "M302" to your start code, this disables the cold-extrusion-prevention, so you can print at temperatures below 170C then.
