### ISSUE TITLE
Question about"Package.sh"

### ISSUE THREAD

**Issue by Fantacy** [daid/LegacyCura#498]
When I ran the "package.sh" in my Ubuntu OS ,it always shows  " mingw32-make command must be somewhere in you $path" .I think "mingw32-make -C CuraEngine" in package.sh can`t works.How shall I solve it?

**Comment by daid** [comment]
"./package.sh debian"

**Comment by Fantacy** [comment]
Thanks for your answer. The installer  under debian is OK. But how can I build the win32 installer?

**Comment by daid** [comment]
For the win32 installer you need a few things, like the mingw compiler, nsis, git-bash

**Comment by danilke** [comment]
Can I make win32 installer on ubuntu?

nsis is already the newest version.
mingw32 is already the newest version

but its still give me when I write "./package.sh win32":
The mingw32-make command must be somewhere in your $PATH.
Fix your $PATH or install mingw: http://www.mingw.org/

**Comment by daid** [comment]
You should be able, but it's is tricky to build the win32 from Ubuntu.

**Comment by felipesanches** [comment]
I am trying to build the Windows installer by using wine.
I did install mingw and I got the same error message that danilke reports:
"The mingw32-make command must be somewhere in your $PATH."

So, I have added it to the path by doing:
export PATH=$PATH:/home/felipe/driveC/MinGW/bin/
and it still complains

So I figured out maybe it was because it was looking for mingw32-make while the binary available is called mingw32-make.exe (with the ".exe" suffix) I am no wine expert. But I wonder if making a symlink called mingw32-make pointing to mingw32-make.exe would fix the issue.

And it did pass the check. Not the script successfully detected the presence of MingW Make and went on and fetched some code repositories from github and when it starts to build the slice engine I get this error message:

process_begin: CreateProcess(NULL, uname, ...) failed.
fixme:ntdll:find_reg_tz_info Can't find matching timezone information in the registry for bias 180, std (d/m/y): 16/02/2014, dlt (d/m/y): 19/10/2014
mingw32-make: Entering directory 'H:/ghmm/Cura/CuraEngine'
g++ -I. -c -Wall -Wextra -O3 -fomit-frame-pointer bridge.cpp -o bridge.o
g++: error: CreateProcess: No such file or directory
Makefile:42: recipe for target 'bridge.o' failed
mingw32-make: **\* [bridge.o] Error 1

**Comment by felipesanches** [comment]
I'm running mingw32-make version 3.82.90-2-cvs-20120902
It was installed by using the MinGW Installation Manager

This link mentions that there is a bug in MinGW-make and suggests patching it to fix:
http://gnu-make.2324884.n4.nabble.com/process-begin-CreateProcess-NULL-quot-quot-failed-td13819.html

Can we confirm that Cura's Makefile does indeed trigger this bug?
Is there anything we can do in order to modify our Makefile so that we workaround this bug?

**Comment by hg42** [comment]
just some thoughts...

if you run it on wine you should probably start it from a windows shell (cmd), else you wouldn't get the windows eco system (environment, .exe, parameter expansion, quoting etc.).
Then it should mostly work like a real windows.

However, you may use a vm to get an even more realistic windows eco system, if wine doesn't work. Of cause this may be difficult to start from a script/batch, but it should be possible with some tricks (e.g. injecting a start batch into the windows file system).

Windows itself could also be replaced by ReactOS to save a windows license.

**Comment by felipesanches** [comment]
In order to workaround the make bug, I manually invoked all of the g++ commands.

In the first attempt, it complained about the target architecture not suporting 64bit instruction set. So I edited the Makefile and added -march=x86-64

A sample command line that I have manually invoked was this:

g++ -I. -c -Wall -Wextra -O3 -fomit-frame-pointer -march=x86-64 utils/logoutput.cpp -o utils/logoutput.o

but in the end it generated an ELF binary because it was using the system-wide g++ from /usr/bin

so I edited the Makefile to use CXX = mingw32-g++

and when I try to manually invoke this:
mingw32-g++.exe -I. -c -Wall -Wextra -O3 -fomit-frame-pointer -march=x86-64 bridge.cpp -o bridge.o

It complains that some DLLs are lacking:

felipe@guarana:~/ghmm/Cura/CuraEngine$ mingw32-g++.exe -I. -c -Wall -Wextra -O3 -fomit-frame-pointer -march=x86-64 bridge.cpp -o bridge.o
err:module:import_dll Library libgmp-10.dll (which is needed by L"C:\mingw\libexec\gcc\mingw32\4.8.1\cc1plus.exe") not found
err:module:import_dll Library libmpc-3.dll (which is needed by L"C:\mingw\libexec\gcc\mingw32\4.8.1\cc1plus.exe") not found
err:module:import_dll Library libmpfr-4.dll (which is needed by L"C:\mingw\libexec\gcc\mingw32\4.8.1\cc1plus.exe") not found
err:module:import_dll Library zlib1.dll (which is needed by L"C:\mingw\libexec\gcc\mingw32\4.8.1\cc1plus.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\mingw\libexec\gcc\mingw32\4.8.1\cc1plus.exe" failed, status c0000135

How do I install those DLLs ?

**Comment by felipesanches** [comment]
The DLLs were already installed at driveC/MinGW/bin/ but I had to edit the windows ergistry by using the regedit tool in order to add the C:\MinGW\bin directory to the windows path in HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment

After doing that, I think I made some progress:

felipe@guarana:~/ghmm/Cura/CuraEngine$ file bridge.o
bridge.o: 80386 COFF executable not stripped - version 30821

Now I'll build all the .c files and link them. Hopefully we can have good news in the next half hour :-)

**Comment by felipesanches** [comment]
Wow! I think I did it :-)

make is now working :-D
Here's what I got in just a few seconds:

felipe@guarana:~/ghmm/Cura/CuraEngine$ file CuraEngine.exe 
CuraEngine.exe: PE32 executable (console) Intel 80386, for MS Windows

**Comment by danilke** [comment]
yuppy!

**Comment by felipesanches** [comment]
ok, next step:

wine: cannot find '/home/felipe/.wine/drive_c/Program Files/NSIS/makensis.exe'

**Comment by felipesanches** [comment]
README.md says: "For Windows the package.sh script can be run from bash using git"
What does it mean?!

**Comment by xiuxiu** [comment]
when you install git on windows, there will be one useful tool "bash" included.
