### ISSUE TITLE
G21 is set twice in start.gcode

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#5]
SkeinPyPy_NewUI/skeinforge_application/alterations/start.gcode contains G21 twice. Is there a reason for this or can the second one be removed?

**Comment by daid** [comment]
G21 sets the printer to "mm" mode. So it gets set to mm mode twice. It won't do harm to remove the 2nd one. I've done so in the code now.

The original SF start code used G21 as "comment" prefix. I removed them because the reason why they where there was no good. It was to preserve the comments in the final GCode, but this did not even work with the "small export".

**Comment by RedwoodForest** [comment]
Great — thanks Daid.

-Larry
