### ISSUE TITLE
Minimum layer time and path order

### ISSUE THREAD

**Issue by illuminarti** [daid/LegacyCura#505]
When printing an object like the classic hollow pyramid (http://www.thingiverse.com/thing:8757), setting minimum layer time helps ensure sufficient cooling.  

However, the path optimization in Steam Engine causes the last corner printed on one layer to be the first corner printed on the next layer, resulting in zero cooling time between layers of that corner.

**Comment by ErikDeBruijn** [comment]
I agree that the path order should be more 'round robin' because it will
ensure that each layer has a more consistent cooling behavior.

Chris Palmer also made this suggestion in 2010. It still makes sense to
have this as the highest-quality setting. If it's a fast print, we could
decide to hop to the nearest island. I don't think that it should ever
switch between clockwise and counter-clockwise for the outer layer. This
always results in visible lines.

http://hydraraptor.blogspot.nl/2010/12/round-robin.html

Met vriendelijke groeten / With kind regards,

Erik de Bruijn MSc.
Co-founder, Ultimaking LTD

2013/7/21 Simon Oliver notifications@github.com

> When printing an object like the classic hollow pyramid (
> http://www.thingiverse.com/thing:8757), setting minimum layer time helps
> ensure sufficient cooling.
> 
> However, the path optimization in Steam Engine causes the last corner
> printed on one layer to be the first corner printed on the next layer,
> resulting in zero cooling time between layers of that corner.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/505
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by daid** [comment]
Actually, I think this can be done smarter. Round-robin is good if your islands are small, but on larger area's the cooling is more then enough for the current method not to negatively impact the print. And thus, without a move, you get a shorter printing time and less strings.

So it should do "if last printed island smaller then X, make sure not starting at this island"

**Comment by ErikDeBruijn** [comment]
That should work, as long as there's no change in clockwise / counter
clockwise direction.

Met vriendelijke groeten / With kind regards,

Erik de Bruijn MSc.
Co-founder, Ultimaking LTD

2013/7/25 daid notifications@github.com

> Actually, I think this can be done smarter. Round-robin is good if your
> islands are small, but on larger area's the cooling is more then enough for
> the current method not to negatively impact the print. And thus, without a
> move, you get a shorter printing time and less strings.
> 
> So it should do "if last printed island smaller then X, make sure not
> starting at this island"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/505#issuecomment-21555670
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by nophead** [comment]
Yes just noticed this problem printing an object with two towers. In my opinion it should always be round robin to give the best thermal consistency. I.e. it gives maximum layer bonding and best cooling so you get better strength as well as better quality. On non-Bowden machines there are never any strings and travel speeds are generally fast enough compared to extrusion speeds the extra travel time is negligible.

 Enrique fixed this in Skeinforge years ago.

**Comment by nallath** [comment]
This is more of a CuraEngine problem.

**Comment by kh90909** [comment]
Have also encountered this problem recently. Especially bad with tall towers as defects in lower layers tend to propagate upwards and grow.

**Comment by richardjm** [comment]
Another call for this issue. Even a cooling tower or multiple cooling towers isn't enough as I can't guarantee the cooling towers are going to be the items suffering from the double layer with 0 cooling time.
