### ISSUE TITLE
13.06.5 Generate GCode Feature

### ISSUE THREAD

**Issue by iceblu3710** [daid/LegacyCura#510]
Can you please re-implement the generate GCode button or have an option to bring it back. My printing computer is a P4 and if I load an entire plate to print the whole machine locks up and slicing can take 10+ minutes.

**Comment by daid** [comment]
Slicing is done on a low prio background thread. If that locks up your computer you should consider upgrading your OS.

(Also, the "real time slicing" is here to stay. I won't budge on it)

**Comment by iceblu3710** [comment]
When I am in my house on my quad core machine I have no problems with real time slicing but if you have an 8" x 8" x " area full of detailed prints and a layer height of 0.05mm it takes quite a bit to chew threw. The CuraEngine is still way faster than the alternatives though so you did do a great job.

I however have a printer in my garage hooked up to a used craigslist computer and telling people to "upgrade their computer" is not really a nice way to deal with requests. As the manual slicing was previously a feature it should be quite a simple task to add an option in expert settings.

A healthy compromise would also be adding a menu entry under expert that toggles the real time slicing. When its disabled then F7 can start slicing. That way you don't even need to deal with opengl graphics changes.

**Comment by daid** [comment]
I did not say "upgrade your computer" I said "upgrade your OS". Your GUI hanging because a low prio background process is doing something is an OS problem. Not sure which OS you are running, but Windows seems to handle this this worst. Note that virus scanners seem to have a significant impact on this bit.

I'm not adding a option. For multiple reasons. I'm not making a compromise on this front. Sorry.
