### ISSUE TITLE
Options gone?

### ISSUE THREAD

**Issue by loelkes** [daid/LegacyCura#515]
Hi,
I just updated from 12.12 to 13.06.5 (downloaded from the UM Website) on OSX 10.8.4. I miss the following options and it would be nice if they could be available in the next releases.
- Support: distance from object
- Printing Order (Infill before Perimeter ...)
- Retraction: extra start length for filament
- Retraction: only retract after $mm of travel
- Retraction: retract on jumps only.

Greetings

**Comment by daid** [comment]
Yes. The 13.06 release switched to a new engine (build from scratch), which was a lot of work. Because of this some features got moved or removed.

The support distance will return (support needs more work, it's not as good as it was)
Printing order is not high on my priority list to add. It adds quite a bit complexity, and tests shown the current order gave the best prints.
Extra length on retraction is silly.
There is a fixed 1.5mm minimal distance before retraction, but this will be made configurable in the future.
Always retract will also make a comeback.

**Comment by loelkes** [comment]
OK cool, thank you. I don't miss the 2nd and 3rd Option anymore, everything works great.
