### ISSUE TITLE
Quick profile selection

### ISSUE THREAD

**Issue by loelkes** [daid/LegacyCura#537]
Hi,
i use multiple/different printers it would be nice to have a quick selection (dropdown?) for profiles. These could be stored in a profile directory.

**Comment by loelkes** [comment]
OK, i have found the recent profile file menu and i can live with it. It would be nice to put this in a tab (like Basic etc.).

**Comment by ErikDeBruijn** [comment]
I think that this is a pretty good idea. It doesn't change functionality to
much, but people will use different profiles more because they're so easy
to access.

With kind regards,

Erik de Bruijn
Co-founder, Ultimaker BV
Op 31 aug. 2013 21:11 schreef "Christian Loelkes" notifications@github.com
het volgende:

> OK, i have found the recent profile file menu and i can live with it. It
> would be nice to put this in a tab (like Basic etc.).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/537#issuecomment-23612122
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT
