### ISSUE TITLE
Heated bed for Ultimaker

### ISSUE THREAD

**Issue by GuyJanssen** [daid/LegacyCura#539]
I am experiencing difficulty in printing larger objects. I now fix the brim to the bed with clips but surely that is not the answer to the problem. I would like to be able to print without the brim.
Will Ultimaker come up with a heated bed for the printer and if so when?

**Comment by ErikDeBruijn** [comment]
Hi, this is more of a sales related question, so in the wrong place, but still a valid one. You can ask at sales@ultimaker.com. Possibly the following reassures you: there will be a major release of something new from Ultimaker, but we will keep our commitment to provide upgrades. The planned upgrades include the heated bed, but we just had too much on our plate to introduce this right now.

I'm closing this issue here, if that's alright, because this is for Cura specific related questions and Cura already has heated bed support.

**Comment by GuyJanssen** [comment]
Thnx Erik and sorry about the wrong place! I'm still trying to find my way ;-) !

**Comment by ErikDeBruijn** [comment]
No problem, your feedback is important to us!

**Comment by GuyJanssen** [comment]
As I found out today it will be on the UM2 so that is a real big help for me once I get it. Thnx!
