### ISSUE TITLE
Travel speed scaled with layer speed

### ISSUE THREAD

**Issue by nophead** [daid/LegacyCura#546]
I have travel speed set to 200, print speed 50, bottom layer speed 20 and infill speed 0.

Cura seems to ramp print speed between 20 and 50 over the first few layers, which seems reasonable but it also scales the travel speed, keeping the 4:1 ratio. Why would you not always travel as fast as possible?

**Comment by ahmetcemturan** [comment]
Hi Nophead,
When I was working on SFACT I added the option to adjust first layer travel speed because the fast travel could rip the freshly laid down extrudate from the printbed.  Especially if your Printbed is not zeroed in perfectly a slower printspeed helps to overcome the first layer.

**Comment by daid** [comment]
ahmetcemturan has an point there. However, this was not done for that reason but because it was quickest to implement.

Luckly, someone got annoyed with it enough to fix it before I got around to do it. So the next version won't do this slowdown anymore. I might need to add something to slow down the travels on the first layer. But that's about it.

**Comment by daid** [comment]
Has been contributed.
