### ISSUE TITLE
Idea: locate part on "non-used" area on platform

### ISSUE THREAD

**Issue by j0uni** [daid/LegacyCura#547]
I've been using non-heated glass on my Ultimaker and it works great. However the glue I use worns out from the middle - from the place where Cura locates prints by default. This idea is suitable when using blue masking tape, that also worns out when you print on the same location (cracks and pops a little off - looses the grip).

I suggest Cura would keep a count of some kind of XY-Grid places where it has printed and tries to locate the part to area where it has printed the least.

Just a simple 10x10 grid and a counter which is incremented whenever print happens (or SD card is written) on that area. Then just relocate parts when added on platform by trial-and-error (placing them in 100 places) and choose the location with lowest "print-count". This is not the most intelligent way but I would say it does the job and causes parts to be printed "all over".

**Comment by ErikDeBruijn** [comment]
I do like the idea, but to keep things predictable this should be an option
to turn on or off. Also, you really want to be able to reset the counters.

Also it shouldn't be too high on the list because it's very easy to drag a
part over to where you want to put it.

With kind regards,

Erik de Bruijn
Co-founder, Ultimaker BV
Op 31 aug. 2013 19:33 schreef "j0uni" notifications@github.com het
volgende:

> I've been using non-heated glass on my Ultimaker and it works great.
> However the glue I use worns out from the middle - from the place where
> Cura locates prints by default. This idea is suitable when using blue
> masking tape, that also worns out when you print on the same location
> (cracks and pops a little off - looses the grip).
> 
> I suggest Cura would keep a count of some kind of XY-Grid places where it
> has printed and tries to locate the part to area where it has printed the
> least.
> 
> Just a simple 10x10 grid and a counter which is incremented whenever print
> happens (or SD card is written) on that area. Then just relocate parts when
> added on platform by trial-and-error (placing them in 100 places) and
> choose the location with lowest "print-count". This is not the most
> intelligent way but I would say it does the job and causes parts to be
> printed "all over".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/daid/Cura/issues/547
> .

## 

Ultimaker - easy, open source 3D printing! http://www.ultimaker.com/
Follow us on Twitter http://twitter.com/ultimaker, Google+https://plus.google.com/u/0/b/105283675489513173942/105283675489513173942/posts
, Facebook http://www.facebook.com/Ultimaker

IMAGINE IT >> MAKE IT

**Comment by daid** [comment]
I think this would confuse more users then that it would help users. You can always look at your bed and avoid damage yourself by dragging the object around.
