### ISSUE TITLE
Help documentation not displaying

### ISSUE THREAD

**Issue by 3PSUK** [daid/LegacyCura#568]
Hi a newbie here. I have just downloaded/installed Cura and accessed Help/online documentation but got this

Whoops our bad...

This page is not printed yet!

I note that the vs downloaded was 3.06.4 although I have seen references to 3.06.5 several times which are  several months old.
Using IEExplorer 9
Pete

**Comment by daid** [comment]
This is due to website migration at Ultimaker. The manual has not been migrated yet, but will be soon.

There is a 13.06.5 for MacOS and Linux available due to some Mac/Linux only bugs. There is also the 13.07 test version from http://software.ultimaker.com/Cura_closed_beta/

A new version of Cura will be released soon to add support for the new Ultimaker2, as well as provide bugfixes and new features.
