### ISSUE TITLE
CuraEngine crashes when slicing models with (lots of) open polygons

### ISSUE THREAD

**Issue by gzaugg** [daid/LegacyCura#572]
How to reproduce:slice a model like this https://www.youmagine.com/designs/volume-voronoi-yoda-by-dizingof (just use "normal quality print" settings)

I tracked it down to an issue in slice.h (line 102). openPolygonList[i] can be empty and causes a memory access violation in that case. So I updated line 100 as follows:

```
            if (openPolygonList[j].size() < 1 || openPolygonList[i].size() < 1) continue;
```

**Comment by gizabit** [comment]
Actually, this would be more appropriate

```
            if (openPolygonList[i].size() < 1) break;
            if (openPolygonList[j].size() < 1) continue;
```

**Comment by daid** [comment]
Actually, line 97 already checks if the openPolyginList[i] is empty.

```
if (openPolygonList[i].size() < 1) continue;
```

However, what seems to happen is when the condition (i == j) on line 107 is true, then the code on line 110:

```
openPolygonList.erase(openPolygonList.begin() + i);
```

Causes a new item to become the item at position i. This could be an empty list and thus causes an exception on the next pass of the loop at line 98.

I think the proper fix is replacing the:

```
openPolygonList.erase(openPolygonList.begin() + i);
```

At line 110 with:

```
openPolygonList[i].clear();
break;
```

The idea here is, that empty openPolygonList items may exists, because removing an item from a vector<> is very expensive time wise. So this should also increase performance a tiny bit.

The same expensive remove is found at line 166.

Great catch!

**Comment by gizabit** [comment]
I couldn't get my head around line 110 last night, wasn't sure if the break there is always appropriate. But you're absolutely right of course.

Btw: Just found https://github.com/Ultimaker/CuraEngine/issues/12 (sorry for putting mine to the wrong project). I think it could be related to this one.
