### ISSUE TITLE
Misc. bugs

### ISSUE THREAD

**Issue by ErikDeBruijn** [daid/LegacyCura#579]
- [ ] Machine settings window is opened (from the menu) but not brought to the foreground
- [ ] Tooltip suggesting: "Set to 0.0 to have the bottom layer thickness the same as the other layers.". Would it be better to just require set to 0 like most other  values?
- [x] Quickprint or full settings should have a check in front of it just like the selected machine. This makes it apparent that's a toggle.
- [x] Group Quick vs. full print and expert settings under the heading "Expert" instead of under "Tools".
- [ ] "The first layer is layer 0" makes sense for programmers, but not for anyone else. The UI should start at 1. (almost a language bug ;) )

**Comment by daid** [comment]
1) Is a Mac only bug. Need to look into it. (It's the usual "window does not show!" stupid bug. No idea what causes it at random)
2) I intentionally set that to 0.0 so indicate you can use sub-mm values, like 0.3. Instead of integer values.
3) Done
4) Done
5) Would break profile backwards compatibility. I think only the fan-layer-nr uses this. And I'm pondering about replacing the layer nr with a height.

**Comment by ErikDeBruijn** [comment]
1) I believe Simon's explanation is quite thorough. You can also let me reproduce the error it if needed. I  can git pull and see if a fix works.
5) I prefer a height as well.

**Comment by loelkes** [comment]
When printing a vase without the 'Spiralize'-Option weird things happen at the inside of the wall. Infill 0%, no top, 0,8mm Shell, Cura 13.11 (this is since the new slicing engine) on OSX 10.9.
![bildschirmfoto 2013-11-21 um 18 16 30](https://f.cloud.github.com/assets/231909/1594131/c3c3609c-52d5-11e3-8174-94fdf16860e7.png)
![bildschirmfoto 2013-11-21 um 18 16 09](https://f.cloud.github.com/assets/231909/1594132/c3d643ba-52d5-11e3-9647-e59fb53125a9.png)

**Comment by daid** [comment]
Those are actually up/down skins. I know you would not expect them there, but they are added to get the proper bottom thickness. (If you go straight down from the yellow lines you'll end up outside the model within the top/bottom thickness length)

Spiralize surpresses this infill.

**Comment by loelkes** [comment]
For me this only makes sense with an infill > 0%.

1) If i understood your answer right it makes sense that these up/down skins are printed under a wall doing an overhang. In the picture it is the opposite.
2) The walls without the skin turned out fine.

My proposition is to suppress them like the rest of the infill if it is set to 0% but i totally understand if you don't agree. This issue is resolved for me since for vases the spiralize function looks great and if i want something with thicker walls i create a shell with some other software before.

**Comment by daid** [comment]
I cannot suppress them, they are part of up/down skin, and I cannot simply suppress up/down skin when you put the infill on 0%, that would be crazy, can cause problems for other models.

**Comment by loelkes** [comment]
OK. Here some more feedback. Thanks for the quick responses.

In my case i want to make hollow christmas balls. Since the spiralize function has no top fill it is not really usefull. I don't understand the difference between a ball/vase with spiralize function and one with 0% infill at the same wall thickness.
With translucent material these skins can be seen.

This is 1.2mm shell, 0% infill and 1mm bottom/top thickness.
![2013-11-28 21 16 20](https://f.cloud.github.com/assets/231909/1642352/e1413d4e-587d-11e3-8447-a595ba62485e.jpg)

Below a screenshot from a part of the wall where for some reason the up/down skin has different patterns (the ball wall is the same).
![screen shot 2013-11-28 at 23 44 48](https://f.cloud.github.com/assets/231909/1642380/bd4fb7ac-587e-11e3-8f82-4df238953e20.png)

Below a screenshot with support. The bottom support was perfect (!). It was a little bit annoying that there was support on the sides because of some minimal overhang from the engraving. Maybe a setting 'Only do support for overhangs over $ mm". I had this problem with some other models too where it would have been easier to rework the model by hand (because the first layer of the overhang was messy) than printing a huge structure.
![screen shot 2013-11-28 at 23 50 05](https://f.cloud.github.com/assets/231909/1642385/a355ee38-587f-11e3-8d9f-a4ea25e4ceab.png)

**Comment by nallath** [comment]
For multiple bugs, create multiple issues. It is very hard to keep track of all fixed bugs if they are piled in one big issue. See; https://github.com/daid/Cura/wiki/Issue-policies
