### ISSUE TITLE
Incorrect processing of a file (tardis)

### ISSUE THREAD

**Issue by revk** [daid/LegacyCura#598]
I have a file that does not process correctly. It shows fine until you do the layer view, and it is then completely wrong. See http://www.me.uk/tardis33.stl

**Comment by daid** [comment]
I'm seeing some very flat duplicate polygons in some parts, which is causing confusion at the CuraEngine. While the model is manifold, it has duplicate faces.

**Comment by revk** [comment]
It was made in openscad, but it should surely not break the processing to have duplicate faces? Are there STL "tidy" tools you can recommend to fix such things (linux)?

**Comment by daid** [comment]
If it's made in OpenSCAD then you most likely have a union with two "boxes" just touching, but due to floating point rounding they are not really touching.

box(20);
translate([20,0,0]) box(20);

Is problematic for example, you should always have some overlap, else the CSG engine from OpenSCAD can also fail.

(But I also want Cura to handle this properly, so I will also work from this side to fix this problem)
