### ISSUE TITLE
Thin walls disappear on slicing.

### ISSUE THREAD

**Issue by n3tg0bl1n** [daid/LegacyCura#606]
Thin walls (0.4) does not show up in the layers view mode (and are not printed either).
This depends on the z axis rotation (for different angles, different parts of walls or entire walls are disappearing). For me, at 0 deg left and right walls are not shown, but for 11 deg, all the walls are there. 
Discovered this while calibrating the flow rate using: http://www.thingiverse.com/download:259710

Using Cura 13.10 on Windows 7.

0 deg rotation
![0degrotation](https://f.cloud.github.com/assets/2899128/1477471/eab14f7e-465b-11e3-8f5b-f8ff1c5d69aa.png)

5 deg rotation
![5degrotation](https://f.cloud.github.com/assets/2899128/1477472/eab2c494-465b-11e3-9537-a5fa517404b5.png)

11 deg rotation
![11degrotation](https://f.cloud.github.com/assets/2899128/1477473/eab58120-465b-11e3-933d-d085ddbecacb.png)

**Comment by daid** [comment]
Known "won't fix" issue. Cura's engine is designed around printing enclosed contours, the 0.4mm thin wall has sections disappearing due to rounding "errors" inside the engine.

If you want a single wall outside box like that, it's much easier to use a solid cube, disable top/bottom and sparse infill.

(I'm also no fan of flow calibration this way, I think it's much better to measure the amount of material going into the feeder. But you are free to do what you prefer)
