### ISSUE TITLE
heated bed prepare doesn't work on UM1

### ISSUE THREAD

**Issue by jngf** [daid/LegacyCura#610]
In cura 13.11 starting a gcodefile with ulticontroller doesn't command the preheating of the bed.
I have to tune it by hand; At first nozzle heating did the same and I am not sure how I fixed this. I experimented with the 2 lines for own temperature settings with no luck.
In the previous version it al was OK.

**Comment by daid** [comment]
Indeed, there is a bug in there. Fixed for the next release. What happens is that the bed is heated up after the nozzle is heated up.

The code becomes:
M109 S220
M190 S70

instead of:
M140 S70
M109 S220
M190 S70

A workaround would be to put:
M140 S{print_bed_temperature}
M109 S{print_temperature}
M190 S{print_bed_temperature}

at the start.gcode.

**Comment by daid** [comment]
(also fixed it for next release)

**Comment by jngf** [comment]
Thanks David,
This was my home maid solution too.

_Met vriendelijke groeten, kind Regards_

_Frans de Jong_
_FabLab Arnhem_
_3D Atelier Arnhem_
_M 06 190 71 287_

2013/11/12 daid notifications@github.com
