### ISSUE TITLE
Cura 13.11.02 Printing not responding

### ISSUE THREAD

**Issue by shape667** [daid/LegacyCura#659]
Hai,

Cura 13.6 no problem, but in 13.11 i can start printing, but then the window freeses and give a not responding error.

Win XP tablet edition.

Han

**Comment by ooxtcoo** [comment]
i have the same problem with windows xp, with windows 7 it works...

solution is, to press again "print" and then it will open the print dialoge without freezing and i can print..

but its anoying to always press 2 times print till it starts...

**Comment by shape667** [comment]
This works thanks

**Comment by jstrebel** [comment]
Daid,
I have made some more checks. (also with 13.11.2)
It looks CURA shuts of when the Extruder exceeds 250°C. 
If I set the Extruder to 248 the the Temperature curve overshoots the preset value of 248 by 3°C. If I set the extruder to 247 then over temp is not triggered.
Doing the same experiment using Pronterface I do not see any Temperature overshoot in the Temperature curve. This means the temperature control loops (PID) are a bit different.

Q: Is Marlin triggering the MAXTEMP or Cura?
What is your recommendation to overcome this?
Right now I do not get reproduceable results sending M143 S260 
Sometime I do not get a MAXTEMP shutoff, sometime it works.

Thank you for your help

Jakob Strebel 

Am 02.01.2014 um 21:45 schrieb shape667 notifications@github.com:

> Using the new firmware in version 13.12 causes my system to turn off the extruder motor after about 1 hour of printing. (tried three times).
> The old firmware keeps printing to the end. 
> hope this helps to find a solution.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> ```
>   WIN 7
> ```

```
  Extruder set to 248C



    Changing monitoring state from 'Offline' to 'Opening serial port'
```

Connecting to: COM5

Connected to: Serial<id=0x3c1aef0, open=True>(port='COM5', baudrate=19200, bytesize=8, parity='N', stopbits=1, timeout=2, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor

Changing monitoring state from 'Opening serial port' to 'Connecting'

Recv: start

Recv: echo: External Reset

Recv: Marlin 1.0.0

Recv: echo: Last Updated: Dec 28 2013 00:11:29 | Author: (none, default config)

Recv: Compiled: Dec 28 2013

Recv: echo: Free Memory: 5420  PlannerBufferBytes: 1232

Recv: echo:Hardcoded Default Settings Loaded

Send: M105

Recv: ok T:73.9 /0.0 B:46.1 /0.0 @:0 B@:0

Changing monitoring state from 'Connecting' to 'Operational'

Send: M105 T0

Recv: ok T:73.5 /0.0 B:46.1 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:73.2 /0.0 B:46.0 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:72.8 /0.0 B:46.0 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:72.5 /0.0 B:46.0 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:72.1 /0.0 B:45.9 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:71.6 /0.0 B:45.9 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:71.2 /0.0 B:45.9 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:70.9 /0.0 B:45.9 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:70.5 /0.0 B:45.8 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:70.2 /0.0 B:45.8 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:69.9 /0.0 B:45.8 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:69.7 /0.0 B:45.8 /0.0 @:0 B@:0

Send: M104 S248

Recv: ok

Send: M105 T0

Recv: ok T:69.5 /248.0 B:45.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:69.8 /248.0 B:45.7 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:71.7 /248.0 B:45.7 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:75.1 /248.0 B:45.7 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:79.2 /248.0 B:45.6 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:82.5 /248.0 B:45.6 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:85.5 /248.0 B:45.6 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:88.9 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:93.3 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:97.4 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:101.0 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:106.3 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:110.6 /248.0 B:45.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:114.7 /248.0 B:45.4 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:118.3 /248.0 B:45.4 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:122.5 /248.0 B:45.4 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:126.7 /248.0 B:45.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:130.9 /248.0 B:45.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:134.6 /248.0 B:45.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:138.3 /248.0 B:45.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:141.7 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:145.2 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:148.6 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:151.5 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:154.5 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:157.0 /248.0 B:45.2 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:159.5 /248.0 B:45.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:162.2 /248.0 B:45.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:165.6 /248.0 B:45.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:168.1 /248.0 B:45.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:172.7 /248.0 B:40.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:179.6 /248.0 B:40.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:185.6 /248.0 B:40.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:189.1 /248.0 B:39.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:192.5 /248.0 B:39.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:195.3 /248.0 B:39.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:198.1 /248.0 B:39.7 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:200.7 /248.0 B:39.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:203.6 /248.0 B:39.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:205.8 /248.0 B:39.5 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:207.8 /248.0 B:39.4 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:209.4 /248.0 B:39.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:211.1 /248.0 B:39.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:212.6 /248.0 B:39.3 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:213.9 /248.0 B:39.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:215.6 /248.0 B:39.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:218.8 /248.0 B:39.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:221.0 /248.0 B:39.0 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:223.0 /248.0 B:38.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:225.0 /248.0 B:38.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:229.1 /248.0 B:38.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:231.7 /248.0 B:38.8 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:235.0 /248.0 B:38.6 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:236.6 /248.0 B:38.6 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:238.8 /248.0 B:38.6 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:240.0 /248.0 B:38.6 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:241.3 /248.0 B:38.3 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:241.4 /248.0 B:38.3 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:241.4 /248.0 B:38.3 /0.0 @:0 B@:0

Send: M105 T0

Recv: ok T:241.3 /248.0 B:38.3 /0.0 @:30 B@:0

Send: M105 T0

Recv: ok T:240.3 /248.0 B:38.1 /0.0 @:115 B@:0

Send: M105 T0

Recv: ok T:240.0 /248.0 B:38.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:239.6 /248.0 B:38.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:240.0 /248.0 B:38.1 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:240.0 /248.0 B:37.9 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:241.3 /248.0 B:37.9 /0.0 @:128 B@:0

Send: M105 T0

Recv: ok T:242.5 /248.0 B:37.9 /0.0 @:126 B@:0

Send: M105 T0

Recv: ok T:243.5 /248.0 B:37.9 /0.0 @:118 B@:0

Send: M105 T0

Recv: ok T:244.8 /248.0 B:37.6 /0.0 @:104 B@:0

Send: M105 T0

Recv: ok T:245.0 /248.0 B:37.6 /0.0 @:126 B@:0

Send: M105 T0

Recv: ok T:246.7 /248.0 B:37.6 /0.0 @:102 B@:0

Send: M105 T0

Recv: ok T:248.3 /248.0 B:37.6 /0.0 @:78 B@:0

Send: M105 T0

Recv: ok T:250.0 /248.0 B:37.5 /0.0 @:52 B@:0

Send: M105 T0

Recv: ok T:251.2 /248.0 B:37.4 /0.0 @:35 B@:0

Recv: Error:0

Recv: : Extruder switched off. MAXTEMP triggered !

Changing monitoring state from 'Operational' to 'Error: 0: Extruder switched...'

Recv: Error:Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)
