### ISSUE TITLE
infill angle

### ISSUE THREAD

**Issue by studiogijs** [daid/LegacyCura#67]
I'd like to have the option to turn the infill. If a long object does not fit on the printbed, but it does when rotated 45 degrees, then the infill must be rotated too.

**Comment by amatiasq** [comment]
+1

**Comment by amatiasq** [comment]
@nallath Any comment about closing this issue? Is it fixed?

**Comment by daid** [comment]
Will never be implemented, too few use cases. (Decision by current maintainers)

**Comment by nallath** [comment]
See; https://github.com/daid/Cura/wiki/Issue-policies

**Comment by amatiasq** [comment]
Is there available any place where the decision is (or has been) discussed?

**Comment by nallath** [comment]
Nope, this was a IRL discussion between me and Daid, as both of us work for UM. If anyone else wants to implement this, they are free to do so.

**Comment by daid** [comment]
While I do listen to a lot of people, and hear a lot of ideas and suggestions for Cura. Almost all of them good for some reason or another. However, I do have ideas about what I do and do not want to do with Cura.
But Cura is not an democracy. I usually have to make a few decisions per week about how to progress in the development. And with every decision I will make a few people unhappy.
Some of these decisions are made by just a gut feeling, others are discussed with my co-workers and friends. But I cannot go around and document every decision. It would take too much time.

I'm not a dictator. I do listen to people. However, I do work like a monarch right now. I have my trusted people, which have a good chance to change my opinion. Everyone else can try to convince me with good arguments. But I do get a lot of "you should do X", reply: "ok, show me actual tests why X is better", _silence_

In this case, it's an extra setting with very limited added value. And one of the reasons why I started Cura is to limit the amount of settings. Which is why it's a no go.

**Comment by amatiasq** [comment]
I agree, I'm also a maintainer and I know you can't make everyone happy, it was just confusing to see the issue closed and not to know what happened :)

Of course I think this feature is important but cura is a awesome piece of software even without it, good job :+1:

**Comment by liutas4x4** [comment]
Huh,

it must to be accessible to tuning:
if you are printing something long, and it lay by diagonal of printing bed, infill will not to be "hardener" of printed body, if one of infill's directions is along long side.

May be there are possibility override this angle in start Gcode?
![infill problem](https://cloud.githubusercontent.com/assets/16444343/12053174/27eaa2fe-af1f-11e5-976b-196f7da2f4fb.png)

**Comment by nallath** [comment]
There is no possibility to override this in the start g-code.

**Comment by liutas4x4** [comment]
Ok.

So, bye Cura - welcome slic3r for this particural project.

**Comment by liutas4x4** [comment]
As you can see, slic3r'ed same thing, which it is impossible to rotate on table because of it's length, now filled with correct pattern - infill work as sup
![infill problem 2](https://cloud.githubusercontent.com/assets/16444343/12055021/a0c199a0-af31-11e5-80b6-a76aeeb6e383.png)
port for weight applied.

**Comment by XiaoShiZi** [comment]
http://manual.slic3r.org/expert-mode/infill-optimization slic3r gives you
the abbillity to change the angle of the infill. Little more parrameters to
master before printing ok like in Cura.
If you need it now realy hard then switch to slic3r otherwise wait till
that option is available in Cura.
same for honeygrid infill. Is stronger infill than rectangular as it's also
used in the airplane industry to have lightweight strong structures ;-)

Greetz,

XiaoShiZi

2015-12-30 19:12 GMT+01:00 liutas4x4 notifications@github.com:

**Comment by liutas4x4** [comment]
You are right about honeycomb, but...
In this project wall-to-wall distance is 8 mm, minus perimeters - honeycomb pattern will not fill correctly such tiny curved space.

**Comment by nallath** [comment]
Buy Cura? Cura is free...

**Comment by liutas4x4** [comment]
Oh no :)
Corrected.
