### ISSUE TITLE
start and end.gcode aren't saved in the .ini

### ISSUE THREAD

**Issue by jgeerds-zz** [daid/LegacyCura#68]
Everytime I do an update to a fresher version of cure, my start and end.gcode's are gone. even though I saved the ini file, and loaded it after the update.

Please save the custom gcodes in the .ini file, or in another place where they don't get constantly overwritten

**Comment by daid** [comment]
The start/end code is stored in the /alteration/ directory. Inside the cura installation directory.

**Comment by jgeerds-zz** [comment]
And I have been replacing the complete Cura folder with the updates from you, hence they get overwritten all the time.
maybe it's worth to think about another place to save the custom gcode, either in another folder, or in the .ini file (where it would make the most sense to me)

**Comment by daid** [comment]
Well, the latest dev version did have some upgrades on the start/end code. So that you got new version isn't that bad ;-)

I had some problems with storing the start/end code in the ini file, which is why I opted for the safe way of having separate files. Also, Slic3r expects files as start/end code. But that can be solved.

I'm leaving this open, because I think it's a good idea to store it in the ini file. But I need to check what the problems where.

**Comment by jgeerds-zz** [comment]
in the mean time, please update the https://github.com/daid/Cura/wiki/Installing-development-version page, mentioning that the alternations folder with custom gcodes will be overwritten in that process.

**Comment by daid** [comment]
I've updated the code to store the start/end code in the profile ini file.
