### ISSUE TITLE
Shortcuts to move the head

### ISSUE THREAD

**Issue by hugokernel** [daid/LegacyCura#71]
Hi and thank you for your work !

I think it would be very usefull to have shortcuts to move the head, mainly for Z axis.

Or eventually, have a window like Control Panel with Replicatorg...

**Comment by daid** [comment]
It indeed is. The development version of Cura has buttons for this already, but they are untested. And most likely do not work because the machine is in absolute mode, and needs to be in relative move mode.

For the time being you can also print with PrintRun, which is also packaged with Cura, mainly because the Cura printing interface is lacking these kinds of features. And PrintRun has them.

**Comment by tachyio** [comment]
hmm actually what I do now is use my hands to twist the z-screw, and move the printing head around the stage. I even turn the extruder screw with my hands before printing to see if the filament is extruding properly. I started doing this when I noticed Cura releases control of the steppers when not printing, which I find to be a very useful feature :)

**Comment by daid** [comment]
RC3 has shortcuts to move the head, and as far as I know they work. So I'm closing this one.
