### ISSUE TITLE
Hot end travels off build area after printing about 3/8 high on Kossel delta

### ISSUE THREAD

**Issue by bplemmons** [daid/LegacyCura#761]
I was using Cura with great success on a Kossel delta printer until recently, Now when the print get up to about 8 mm tall, The print head fly's off between towers z and y, crashing the machine, I've tried several different parts and even when back to some older versions of Cura, but same result. I've checked my printer size and center is 0,0 for delta but I'm stumped.....;(

Bill

**Comment by nallath** [comment]
Did you have the same behaviour with other slicing engines?

**Comment by daid** [comment]
Please verify that the move is actually in the GCode and not a communication/firmware issue.

The move off the platform should be visible in the layerview, you can also verify the GCode with RepetierHost to see if there is an odd move.

(14.02RC2 to 14.02RC4 have this problem with dual-color prints, which has been fixed in that latest RC)

Please re-open if the required info is provided.

**Comment by bplemmons** [comment]
Hello,

I did verify the layers in both cura and repetier,
I ended up removing it from my pc and reinstalling it, now it works...  :)

Bill

On Wednesday, March 5, 2014 4:00 AM, daid notifications@github.com wrote:

Please verify that the move is actually in the GCode and not a communication/firmware issue.
The move off the platform should be visible in the layerview, you can also verify the GCode with RepetierHost to see if there is an odd move.
(14.02RC2 to 14.02RC4 have this problem with dual-color prints, which has been fixed in that latest RC)
Please re-open if the required info is provided.
