### ISSUE TITLE
Skin setting messes up layer count in Gcode view of model

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#77]
Normally a printed layer corresponds to a layer as displayed in the Gcode view in Cura, but when I turn on Skin the Gcode view shows 3 times as many layers (i.e. a print which had 65 layers (and which will print 65 layers disregarding the outer shell) now has 195 layers in the Gcode view).

It appears that the three layers correspond to inner wall, outer wall, fill in that order.

**Comment by daid** [comment]
I noticed the same, the problem is that the GCode preview sees every Z change as a new layer. So during the skin it changes the Z twice, causing 2 more layers to show up. I do not have an easy fix right now, because it also uses the different layers to calculate the line thickness in the preview.

Same problem can happen with Joris enabled, which causes even more weirdness to happen in the preview.

And thanks for all the issue reports and bug fix! It really helps in getting the quality up.

**Comment by RedwoodForest** [comment]
Yeah, that makes sense.

I had the thought that maybe you could use the ";LAYER:#" comments as a hint (if the comments were present batch all Z changes up to the next layer comment into a single layer), but that would only work for GCode generated by Cura.

I'm glad you're finding them helpful. I, in turn, appreciate the work you've done to fix them and the speed at which you've done it. You've made an impressive amount of progress in the month or two I've had my Ultimaker.

**Comment by daid** [comment]
I could use the layer comments, and fall back to the old code if they layer comments are not found. But then I still need the layer thickness for the line width. The whole GCode preview is a bit of a hack right now and could use a rewrite, as it's also slow to change layers.

**Comment by RedwoodForest** [comment]
Just a note that this is far worse when viewing GCode for something like http://www.thingiverse.com/thing:21042 with a bunch of separate pieces in one STL. In my case for a print that's actually 39 layers the viewer has 441.
