### ISSUE TITLE
Feature request - z axis travel speed

### ISSUE THREAD

**Issue by Prof62** [daid/LegacyCura#776]
Is there any possibility of adding a Z-Axis travel speed parameter?

I know that all moves are done at travel speed with the assumption that the printer will be set up to limit the actual speed. However, given that many machines support a vastly different maximum speed for Z compared to X and Y and the firmware defaults are not always sensible, a Z speed would save a lot of potential headaches.

Also, some machines with dual Z-Axis motors (e.g. Mendals, etc) can get badly out of sync if you drive Z to fast - With catastrophic results for hot ends and printer beds.

A nice to have, yes, but many people are blissfully unaware of the intricacies of their printer firmware until the day they run that first print using Cura and that horrible grinding noise starts accompanied by flying Kapton tape.

**Comment by daid** [comment]
Limit the feedrate in firmware. Not adding a setting for people who are to lazy to setup their firmware properly.

With marlin you could put "M203 Z300" in the start code to limit to 5mm/s

**Comment by Prof62** [comment]
In my case it was incompetence rather than laziness but I take your point.

**Comment by wjsteele** [comment]
Actually, M203 is in mm/s, so the correct limit would be M203 Z5 for 5 mm/s.

**Comment by lciscon** [comment]
Actually setting the feed rate in firmware is not the same as setting it in the slicer.  Volume and extrusion rate calculations would be incorrect especially if any kind of multi-point bed leveling is used.  The slicer really should know the correct value.

**Comment by daid** [comment]
@lciscon you are wrong, as extrusion is expressed in amount of extrusion per movement, not per time. So if you change the move speed, it also correctly adjusts the extrusion speed. This was done 5 years ago.

**Comment by lciscon** [comment]
Exactly.  So the extrusion per movement assumes it knows the rate of movement. If the actual movement speed differs from the expected speed (because the firmware overrode the commanded speed due to rate limitations) then the flow rate is incorrect.  I can demonstrate quantitative results to that effect if you want.

**Comment by daid** [comment]
There is no "flow rate". It's a none-existing term that is meaningless in this context. There is no flow rate calculation. Nowhere. Not in Cura, not in the firmware.

Any "error" you might see is because of mechanical issues/limits/errors, not software.

**Comment by lciscon** [comment]
I am defining "flow rate" in this context as the "amount of extrusion per movement".  The amount of extrusion per movement assumes that the movement actually executed matches the amount of movement commanded.  That is not necessarily the case if you hit a Z rate limit that is 1/10 (or less) the X/Y rate limits. In a way you are correct that it is a kind of mechanical failure/limitation.  However it is one that can be easily fixed in the software.  Other slicers include this capability.

Obviously you clearly believe you are right and nothing I say will modify your belief.  There is no point in continuing this discussion.  Thanks for your time.

**Comment by daid** [comment]
The amount of movement does not change when you hit Z rate limits, only the speed at which this movement is done. So there is a command to "move from A to B, and during this move do C amount of extrusion. And do this move at speed D", if the speed is limited, it does not change C, it does not change A or B. It only changes D.
Also, unless you use spiralize, there is never a Z move with extrusion.

I hope you understand that I AM right. After all, I did program the CuraEngine that generates the GCode, and I fully understand how Marlin works as I've done a shitload of work on that as well.

**Comment by BagelOrb** [comment]
Although he is a bit blunt, daid is right here, unless there is some huge misunderstanding and you are talking about wholly different than we think.

There is quite a possibility that z speed will be editable in a couple of months, although daid is making a good case only putting it in the firmware.
