### ISSUE TITLE
GCode is not displayed for project planner print

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#88]
If I slice a set of objects using the project planner the GCode is not displayed in the Cura preview window.

It is possible to work around this by renaming the gcode file to match the file name of a normally sliced print and reloading the STL for that print (e.g. If you have myprint.stl you can rename your project slice to myprint_export.gcode and reload the STL in Cura). 

This is useful to me because I like to look at how things like infill and narrow walls came out, expected print cost/time, etc.

I'm sure you're planning on taking care of this, but since it's one of the biggest outstanding issues for me with regards to the project planner I thought I'd go ahead and file it.

**Comment by daid** [comment]
It is somewhere in the planning, but I'm not sure how and when yet.

I've just done a pretty large change to the normal GCode preview, which should be a lot faster now. But the preview code is still a bit messy.

Also, because slicing in the project planner takes quite a while, I usually start the project planner slice, and then change my plan for the next slice. You can even run multiple project plan slices at the same time. So viewing the result in the project plan viewer would be a bit odd I think. On the other hand, it should be doable.
However, the project planner view lacks zooming/panning for top down view. Making GCode inspection harder.

Expected print time/filament use should be quite simple to add to the final status, like I did for the normal slicing a few days ago.

**Comment by RedwoodForest** [comment]
That makes sense.

I was originally assuming it would be in the preview window where normal slices are displayed, probably because I assumed you were going to allow printing it from there as well (which is currently also unsupported without a workaround, though I don't care much about because I always print from my UltiController).

Expected use statistics would be useful.

**Comment by daid** [comment]
(Cleaning up old issues, as far as I know this issue is deprecated due to updates on Cura)
