### ISSUE TITLE
Start/End GCode editor does not allow horizontal scrolling using Trackpad

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#89]
On my Macbook Pro the new GCode editor window can not be scrolled horizontally using the trackpad. Vertical trackpad scrolling works correctly.

**Comment by fuegas** [comment]
Unfortunately, this is a bug which we cannot fix.
From the [wxPython-users list](http://wxpython-users.1045709.n5.nabble.com/GenericDirCtrl-broken-on-2-8-4-2-td2361331.html):

> Thanks.  The support for horizontal wheel scrolling isn't implemented in 
> 2.8, and it ended up doing a divide by zero.  I can at least protect 
> against that, but full support for horizontal wheel scrolling will have 
> to wait until 2.9 as it requires a binary incompatible change. 

Although the title suggest the problem is about GenericDirCtrl, this is related to the problem you describe.
On my Macbook I can't scroll horizontally using the trackpad either.

You can find the recent changes at http://wxpython.org/CHANGES.html
Alas, there is no mention of a fix for horizontal scrolling on OSX...
So we have to wait until they fix this.

**Comment by RedwoodForest** [comment]
Good to know the issue is known. Thanks for looking into it.

It looks like there are a bunch of horizontal scrolling bugs in their bug tracker in various states: http://trac.wxwidgets.org/search?q=horizontal+scroll

Do you know which one(s) are related to this issue?

**Comment by fuegas** [comment]
[This search](http://trac.wxwidgets.org/query?status=accepted&status=confirmed&status=infoneeded&status=infoneeded_new&status=new&status=portneeded&status=reopened&component=wxOSX-Cocoa&summary=~horizontal&summary=~scroll&order=priority) narrows the results down quite a bit :)
[The latest](http://trac.wxwidgets.org/ticket/13729), only 5 months old, request the implementation of swipe, pinch and horizontal scrolling...
So I guess we'll have to wait quite some time before it comes available...
