### ISSUE TITLE
Auto placing many objects in project planner can place objects off the print bed

### ISSUE THREAD

**Issue by RedwoodForest** [daid/LegacyCura#92]
I attempted to auto place an entire set of pieces for http://www.thingiverse.com/thing:22018, which doesn't fit on the bed, so they ended up getting placed overhanging the sides.

When placing pieces manually you're not permitted to do this.

Perhaps a warning message would be appropriate in this case?

**Comment by daid** [comment]
I kinda hate popup messages, because they break workflow. But maybe I should always make sure all the objects are at least on the bed, even if they would hit each other during printing then. If they would hit after auto-placing you would instantly see that then because they turned red.

The auto placement tool is not that perfect. I have some ideas on improving it. It currently already tries a bunch of different layouts and selects the one that uses the least amount of print area. But it could also re-order the parts for better spacing.
An issue with this would be that the amount of possible options to check grows exponential. With 3 objects there are 6 combinations to check then, but with 8 objects, there are 40320 combinations. And with 20 objects you would have 2432902008176640000 combinations.

Still, the barrel puzzle might just fit on the Ultimaker, but you would need a damn smart algorithm to figure that out. I think if you use the right order of parts, and rotate a few of them, and manually place them, they could fit.

**Comment by RedwoodForest** [comment]
Ah, the bin packing problem.

I wonder if there are any good (but non-optimal) algorithms available.
Seems like there should be a lot of info out there since it's such a
well known problem (I'm on my phone at the moment which makes it slow
to look now).

On May 4, 2012, at 7:25 AM, daid
reply@reply.github.com
wrote:

**Comment by daid** [comment]
It's more like a complex packing problem: http://en.wikipedia.org/wiki/Packing_problem

Where the shapes you are trying to pack have different sizes, and the shape depends on the order in which you place the shape.

The advantage of the current implementation is that it work pretty good for the same sized objects. I think I'll keep the current implementation while I work on more pressing issues, like the ability to print a project, and view it's GCode. But first I have to fix the "first run wizard". I should build a new release soon, there are so many fixes and updates compared to RC2.

**Comment by RedwoodForest** [comment]
You're right of course that's it's more complex than the simple bin packing problem.

It also makes sense that this is not a particularly pressing issue. It's a problem I personally find interesting, but even if you found a near-optimal algorithm that be run with no perceptible delay I don't think 90% of users would notice or care:).
