### ISSUE TITLE
Unexplained, random shutdown of Ultimaker during prints

### ISSUE THREAD

**Issue by tachyio** [daid/LegacyCura#96]
Currently printing with the Windows version of Cura RC2, and the Ultimaker has randomly shutdown twice during 2 prints with Cura's printrun (the little window that pops up when you click Print GCode).

Attempting to reconnect to the Ultimaker fails, and the only remedy is to power on/off, followed by unplugging the usb to reset it.

I also notice that the computer is continuing to send a control signal to the fan even after I turn off the main A/C, causing it to spin intermittently, as presumably USB voltage isn't high enough for it. Only after unplugging the USB, does everything go back to normal.

Weird.

**Comment by tachyio** [comment]
Okay I found the error stated in the console:

https://plus.google.com/photos/104220463645938697004/albums/5739556552189258337/5739556551129241778

Something about write-timeout.

I guess it could mean a serial communications error, or firmware error of sorts.

**Comment by tachyio** [comment]
Hmm I think this might be related to the issue:

http://forum.ultimaker.com/viewtopic.php?f=15&t=730&p=4744#p4744

**Comment by daid** [comment]
I could catch the error more gracefully, which I will do. But the problem is in the USB connection, which seems to stop working. As it fails to reconnect afterwards. And you need to unplug USB.

I actually have a laptop that acts the same on USB, and it's a real pain to print anything with it. I've read somewhere that there are powersave settings somewhere in windows that you can disable, and that that seems to help.

**Comment by tachyio** [comment]
Windows power mode is high performance with USB suspend set to disabled. Unless windows is as buggy as repg and disabled = enabled haha!

I restarted the pc cos I remembered I ran some updates on it previously and didn't restart, seems to be printing normally now for 30 minutes. The confounding thing is that this issue just appeared out of nowhere, printer was fine for 2 days straight since the last bad jam. I'll probably swap USB ports later if this print fails, but it's ok so far.

Also is there a theory on jamming? I was thinking its related to the maximum possible flow rate of PLA at any given temperature...so ive done some simple math:

Cross sectional area of extruded filament (from nozzle) \* extrusion velocity = extrusion volume / second

PI \* (0.2 / 2)^2 \* 100 = 3.14mm3/sec

I found my maximum to be 3.14mm3/sec, at 220C using 0.2mm layer height at 100mm/s

If I exceed that by doing say 0.3mm layer height at 75mm/s, which means about 5.70mm3/sec, the extruder jams.

Not sure if the math is correct though.

**Comment by daid** [comment]
My theory in jammer is that it's only possible if you have a gap between the brass/peek/bowden tube. Because if you do not have a gap, then any molten filament that gets into the bowden tube can be pressed into the hotend again. As the hotend has a slightly larger diameter then the bowden tube.

People have printed with 10mm3/sec, but the faster you go the higher temperature you need, as you need to melt the filament faster.

Cura RC2 has a tooltip on the speed which tells you how much filament you are extruding :-) so you don't need to do the math yourself.

**Comment by tachyio** [comment]
Okay :) just squeezing out an awesome 0.1mm yoda print in translucent green. It's knockin my socks off!! So awesome :)
