### ISSUE TITLE
start.gcode is not actually the start of gcode generated by Cura 14.09

### ISSUE THREAD

**Issue by lordofhyphens** [daid/LegacyCura#974]
Related to #973. 

The temperature settings from the cura GUI are being inserted in the gcode before start.gcode is placed. In real-world terms, this swap around means that I am unable to preheat my bed using start.gcode before my hotend. I can't do an initial retract either, for the same reasons. 
## GCODE snippet from a 10x10x10 cube. 

M140 S70.000000
M109 T0 S220.000000
T0
M190 S70.000000
;Sliced at: Tue 07-10-2014 15:39:53
;Basic settings: Layer height: 0.1 Walls: 0.8 Fill: 20
;Print time: #P_TIME#
;Filament used: #F_AMNT#m #F_WGHT#g
;Filament cost: #F_COST#
M190 S110;Uncomment to add your own bed temperature line -- custom bed  temp
M109 S235 ;Uncomment to add your own temperature line
G21        ;metric values
G90        ;absolute positioning
M82        ;set extruder to absolute mode
M107       ;start with the fan off

G28 X0 Y0  ;move X/Y to min endstops
G28 Z0     ;move Z to min endstops

G1 Z15.0 F9000 ;move the platform down 15mm

G92 E0                  ;zero the extruded length
G1 F200 E3              ;extrude 3mm of feed stock
G92 E0                  ;zero the extruded length again
G1 F9000
;Put printing message on LCD screen
M117 Printing...

;Layer count: 98
;LAYER:0
M107
G0 F9000 X90.000 Y83.500 Z0.300

**Comment by gwadej** [comment]
I've run into the same problem.

To clarify a bit, even using the start.gcode variant, the only way to remove the initial heating commands is by setting the temperatures to 0 in the interface (unless I am missing something).

This means that the temperatures now have to be hardcoded in the start code instead of configurable. I can see me changing the temperature in the configuration some time from now, when I've forgotten the issue and causing new problems all over again.

**Comment by daid** [comment]
https://github.com/daid/Cura/blob/SteamEngine/Cura/util/profile.py#L1262
That's the code where the temperature lines are added. If it sees the {print_temperature} tag in the manual start code, it will not add this line.

**Comment by gwadej** [comment]
I stand corrected. That takes care of my issue.
